(*****************************************************************************
  Program:     Setup
  Authors:     Lablogic
******************************************************************************)

program Setup;

{%ToDo 'Setup.todo'}

uses
  Forms,
  Windows,
  Classes,
  ExtCtrls,
  StdCtrls,
  SysUtils,
  CodeSite in 'System\Debug\CodeSite\CodeSite.pas' {FrmCodeSite},
  Boot in 'System\Boot\Boot.pas',
  llCache in 'System\llCache.pas',
  About in 'Main\ABOUT.PAS' {FrmAbout},
  AddManager in 'Interface\Action\Add\AddManager.pas',
  AddManagerInterfaces in 'Interface\Action\Add\AddManagerInterfaces.pas',
  Advertiser_TLB in 'System\IdleOrBusy\Advertiser_TLB.pas',
  AEConnect in 'System\Startup\AEConnect.pas',
  AEForceUserLogout in 'System\Startup\AEForceUserLogout.pas',
  AEPostConnect in 'System\Startup\AEPostConnect.pas',
  AEPostForceUserLogout in 'System\Startup\AEPostForceUserLogout.pas',
  AEPostReadyToGo in 'System\Startup\AEPostReadyToGo.pas',
  AEPostStartup in 'System\Startup\AEPostStartup.pas',
  AEPostUpgrade in 'System\Startup\AEPostUpgrade.pas',
  AEPreConnect in 'System\Startup\AEPreConnect.pas',
  AEPreForceUserLogout in 'System\Startup\AEPreForceUserLogout.pas',
  AEPreReadyToGo in 'System\Startup\AEPreReadyToGo.pas',
  AEPreStartup in 'System\Startup\AEPreStartup.pas',
  AEPreUpgrade in 'System\Startup\AEPreUpgrade.pas',
  AEReadyToGo in 'System\Startup\AEReadyToGo.pas',
  AEStartup in 'System\Startup\AEStartup.pas',
  AEUpgrade in 'System\Startup\AEUpgrade.pas',
  Analyse in 'Element\analyse\Analyse.PAS',
  AnalyseDataAccess in 'Element\analyse\AnalyseDataAccess.PAS',
  AnalyseFrame in 'Element\analyse\AnalyseFrame.PAS',
  AnalyseInterfaces in 'Element\analyse\AnalyseInterfaces.PAS',
  AnalyseIs in 'Element\analyse\AnalyseIs.PAS',
  AnalyseIsDataAccess in 'Element\analyse\AnalyseIsDataAccess.PAS',
  AnalyseIsFrame in 'Element\analyse\AnalyseIsFrame.PAS',
  AnalyseIsInterfaces in 'Element\analyse\AnalyseIsInterfaces.PAS',
  AnalyseIsSection in 'Element\analyse\AnalyseIsSection.PAS',
  AnalyseSection in 'Element\analyse\AnalyseSection.PAS',
  ApplicationInterfaces in 'System\Configuration\ApplicationInterfaces.pas',
  Apply in 'Element\Attribute\Apply.pas',
  ApplyDataAccess in 'Element\Attribute\ApplyDataAccess.pas',
  ApplyFrame in 'Element\Attribute\ApplyFrame.PAS',
  ApplyInterfaces in 'Element\Attribute\ApplyInterfaces.pas',
  ApplySection in 'Element\Associate\ApplySection.PAS',
  AQDebug in 'System\AQTest\AQDebug.pas',
  Associate in 'Element\Associate\Associate.PAS',
  Associated in 'Element\Associate\Associated.PAS',
  AssociateDataAccess in 'Element\Associate\AssociateDataAccess.PAS',
  AssociatedDataAccess in 'Element\Associate\AssociatedDataAccess.PAS',
  AssociatedFrame in 'Element\Associate\AssociatedFrame.PAS' {FraAssociated: TFrame},
  AssociatedInterfaces in 'Element\Associate\AssociatedInterfaces.PAS',
  AssociatedSection in 'Element\Associate\AssociatedSection.PAS',
  AssociateFrame in 'Element\Associate\AssociateFrame.PAS' {FraAssociate: TFrame},
  AssociateInterfaces in 'Element\Associate\AssociateInterfaces.PAS',
  AssociateIs in 'Element\Associate\AssociateIs.PAS',
  AssociateIsDataAccess in 'Element\Associate\AssociateIsDataAccess.PAS',
  AssociateIsFrame in 'Element\Associate\AssociateIsFrame.PAS' {FraAssociateIs: TFrame},
  AssociateIsInterfaces in 'Element\Associate\AssociateIsInterfaces.PAS',
  AssociateIsSection in 'Element\Associate\AssociateIsSection.PAS',
  AssociateSection in 'Element\Associate\AssociateSection.PAS',
  Attribute in 'Element\Attribute\Attribute.pas',
  AttributeDataAccess in 'Element\Attribute\AttributeDataAccess.pas',
  AttributeFloatFrame in 'Element\Attribute\AttributeFloatFrame.pas' {FraAttributeFloat: TFrame},
  AttributeInterfaces in 'Element\Attribute\AttributeInterfaces.pas',
  AttributeIs in 'Element\Attribute\AttributeIs.pas',
  AttributeIsBrowse in 'Element\Attribute\AttributeIsBrowse.pas',
  AttributeIsDataAccess in 'Element\Attribute\AttributeIsDataAccess.pas',
  AttributeIsFrame in 'Element\Attribute\AttributeIsFrame.pas' {FraAttributeIs: TFrame},
  AttributeIsInterfaces in 'Element\Attribute\AttributeIsInterfaces.pas',
  AttributeIsSection in 'Element\Attribute\AttributeIsSection.pas',
  AttributeManager in 'Element\Attribute\AttributeManager.pas',
  AttributeManagerInterfaces in 'Element\Attribute\AttributeManagerInterfaces.pas',
  AttributeSection in 'Element\Attribute\AttributeSection.pas',
  Auditevent in 'System\Audit\Auditevent.PAS',
  AuditeventDataAccess in 'System\Audit\AuditeventDataAccess.PAS',
  AuditeventFrame in 'System\Audit\AuditeventFrame.PAS' {FraAuditevent: TFrame},
  AuditeventInterfaces in 'System\Audit\AuditeventInterfaces.PAS',
  AuditeventSection in 'System\Audit\AuditeventSection.PAS',
  AuditPreview in 'System\Audit\AuditPreview.pas' {FrmAuditPreview},
  Auditreason in 'System\Audit\Auditreason.PAS',
  AuditreasonDataAccess in 'System\Audit\AuditreasonDataAccess.PAS',
  AuditreasonFrame in 'System\Audit\AuditreasonFrame.PAS' {FraAuditreason: TFrame},
  AuditreasonInterfaces in 'System\Audit\AuditreasonInterfaces.PAS',
  AuditreasonSection in 'System\Audit\AuditreasonSection.PAS',
  Backdoor in 'System\Security\Backdoor.PAS' {FrmBackDoor},
  BackdoorDataAccess in 'System\Security\BackdoorDataAccess.pas',
  Barcode in 'System\Barcode\BARCODE.PAS',
  BasicInterfaces in 'System\Thing\BasicInterfaces.pas',
  bdeOracleDB in 'System\Database\bdeOracle\bdeOracleDB.pas',
  bdeOracleDBQuery in 'System\Database\bdeOracle\bdeOracleDBQuery.pas',
  bdeOracleDBSession in 'System\Database\bdeOracle\bdeOracleDBSession.pas',
  bdeOracleDBTypes in 'System\Database\bdeOracle\bdeOracleDBTypes.pas',
  bdeStandardDB in 'System\Database\bdestandard\bdeStandardDB.pas',
  bdeStandardDBQuery in 'System\Database\bdestandard\bdeStandardDBQuery.pas',
  bdeStandardDBSession in 'System\Database\bdestandard\bdeStandardDBSession.pas',
  bdeStandardDBTypes in 'System\Database\bdestandard\bdeStandardDBTypes.pas',
  Browse in 'Interface\Browse\Browse.pas',
  BrowseHelper in 'Interface\Browse\BrowseHelper.pas',
  BrowseInterfaces in 'Interface\Browse\BrowseInterfaces.pas',
  BrowseManager in 'Interface\Browse\BrowseManager.pas',
  BrowseManagerInterfaces in 'Interface\Browse\BrowseManagerInterfaces.pas',
  BrowseTemplate in 'Interface\Browse\BrowseTemplate.pas' {FrmBrowseTemplate},
  Cache in 'System\Cache\Cache.pas',
  CacheDebugger in 'System\Cache\CacheDebugger.pas' {fraDebugCacheFrame: TFrame},
  CacheHelper in 'System\Cache\CacheHelper.pas',
  CacheInterfaces in 'System\Cache\CacheInterfaces.pas',
  Calculator in 'Interface\Miscellaneous\calculator.pas' {fmCalculator},
  Check in 'Utils\Check.pas',
  ClassTypes in 'System\Heirachy\ClassTypes.pas',
  Clipboard in 'System\Clipboard\Clipboard.pas',
  ClipboardInterfaces in 'System\Clipboard\ClipboardInterfaces.pas',
  cLLComboBox in 'Components\cLLComboBox.pas',
  cLLComboBoxs in 'Components\cLLComboBoxs.pas',
  cLLListBox in 'Components\cLLListBox.pas',
  cLLVersionInfo in 'Components\cLLVersionInfo.pas',
  Clock in 'System\Clock\Clock.pas',
  ClockDataAccess in 'System\Clock\ClockDataAccess.pas',
  ClockInterfaces in 'System\Clock\ClockInterfaces.pas',
  CMBTL5 in 'TP\LL\Cmbtl5.pas',
  Collection in 'Element\Collection\Collection.pas',
  CollectionBrowse in 'Element\Collection\CollectionBrowse.pas' {FrmCollectionBrowse},
  CollectionDataAccess in 'Element\Collection\CollectionDataAccess.pas',
  CollectionFrame in 'Element\Collection\CollectionFrame.PAS' {FraCollection: TFrame},
  CollectionhIstory in 'Element\Collection\CollectionhIstory.PAS',
  CollectionhIstoryDataAccess in 'Element\Collection\CollectionhIstoryDataAccess.PAS',
  CollectionhIstoryFrame in 'Element\Collection\CollectionhIstoryFrame.PAS' {FraCollectionhIstory: TFrame},
  CollectionhIstoryInterfaces in 'Element\Collection\CollectionhIstoryInterfaces.PAS',
  CollectionhIstorySection in 'Element\Collection\CollectionhIstorySection.PAS',
  CollectionInterfaces in 'Element\Collection\CollectionInterfaces.pas',
  CollectionIs in 'Element\Collection\CollectionIs.pas',
  CollectionIsAttributeIs in 'Element\Collection\CollectionIsAttributeIs.pas',
  CollectionIsAttributeIsFrame in 'Element\Collection\CollectionIsAttributeIsFrame.pas' {FraCollectionIsAttributeIs: TFrame},
  CollectionIsAttributeIsInterfaces in 'Element\Collection\CollectionIsAttributeIsInterfaces.pas',
  CollectionIsAttributeIsSection in 'Element\Collection\CollectionIsAttributeIsSection.pas',
  CollectionIsBrowse in 'Element\Collection\CollectionIsBrowse.pas',
  CollectionIsDataAccess in 'Element\Collection\CollectionIsDataAccess.pas',
  CollectionIsFrame in 'Element\Collection\CollectionIsFrame.pas' {FraCollectionIs: TFrame},
  CollectionIsInterfaces in 'Element\Collection\CollectionIsInterfaces.pas',
  CollectionIsSection in 'Element\Collection\CollectionIsSection.pas',
  CollectionManager in 'Element\Collection\CollectionManager.pas',
  CollectionManagerInterfaces in 'Element\Collection\CollectionManagerInterfaces.pas',
  CollectionSection in 'Element\Collection\CollectionSection.PAS',
  Collectionsnapshot in 'Element\Collection\Collectionsnapshot.PAS',
  CollectionsnapshotDataAccess in 'Element\Collection\CollectionsnapshotDataAccess.PAS',
  CollectionsnapshotFrame in 'Element\Collection\CollectionsnapshotFrame.PAS' {FraCollectionsnapshot: TFrame},
  CollectionsnapshotInterfaces in 'Element\Collection\CollectionsnapshotInterfaces.PAS',
  CollectionsnapshotSection in 'Element\Collection\CollectionsnapshotSection.PAS',
  Combination in 'Element\Combination\Combination.PAS',
  Combinationattribute in 'Element\Combination\Combinationattribute.PAS',
  CombinationattributeDataAccess in 'Element\Combination\CombinationattributeDataAccess.PAS',
  CombinationattributeFrame in 'Element\Combination\CombinationattributeFrame.PAS' {FraCombinationattribute: TFrame},
  CombinationattributeInterfaces in 'Element\Combination\CombinationattributeInterfaces.PAS',
  CombinationattributeSection in 'Element\Combination\CombinationattributeSection.PAS',
  CombinationDataAccess in 'Element\Combination\CombinationDataAccess.PAS',
  CombinationFrame in 'Element\Combination\CombinationFrame.PAS' {FraCombination: TFrame},
  CombinationInterfaces in 'Element\Combination\CombinationInterfaces.PAS',
  CombinationSection in 'Element\Combination\CombinationSection.PAS',
  COMHelper in 'System\Extension\COMHelper.pas',
  ComObjEx in 'System\Extension\ComObjEx.pas',
  Complex in 'System\Dimension\Complex.pas',
  ComplexBrowse in 'System\Dimension\ComplexBrowse.pas' {FrmComplexBrowse},
  ComplexDataAccess in 'System\Dimension\ComplexDataAccess.pas',
  ComplexFrame in 'System\Dimension\complexframe.pas' {FraComplex: TFrame},
  ComplexInterfaces in 'System\Dimension\ComplexInterfaces.pas',
  ComplexSection in 'System\Dimension\ComplexSection.pas',
  ComplexTypes in 'System\Dimension\ComplexTypes.pas',
  Compound in 'Element\Compound\Compound.PAS',
  CompoundDataAccess in 'Element\Compound\CompoundDataAccess.PAS',
  CompoundFrame in 'Element\Compound\CompoundFrame.PAS' {FraCompound: TFrame},
  CompoundInterfaces in 'Element\Compound\CompoundInterfaces.PAS',
  CompoundIs in 'Element\Compound\CompoundIs.PAS',
  CompoundIsDataAccess in 'Element\Compound\CompoundIsDataAccess.PAS',
  CompoundIsFrame in 'Element\Compound\CompoundIsFrame.PAS' {FraCompoundIs: TFrame},
  CompoundIsInterfaces in 'Element\Compound\CompoundIsInterfaces.PAS',
  CompoundIsSection in 'Element\Compound\CompoundIsSection.PAS',
  CompoundSection in 'Element\Compound\CompoundSection.PAS',
  Configuration in 'System\Configuration\Configuration.pas',
  ConfigurationFrame in 'Interface\Configuration\ConfigurationFrame.pas' {FraConfiguration: TFrame},
  ConfigurationInterfaces in 'System\Configuration\ConfigurationInterfaces.pas',
  ConfigurationSection in 'Interface\Configuration\ConfigurationSection.pas',
  ConfigurationStore in 'System\Configuration\ConfigurationStore.pas',
  ConfigurationStoreInterfaces in 'System\Configuration\ConfigurationStoreInterfaces.pas',
  Contact in 'System\Contact\Contact.pas',
  Contact2 in 'System\Contact\Contact2.pas',
  ContactDataAccess in 'System\Contact\ContactDataAccess.pas',
  ContactFrame in 'System\Contact\ContactFrame.PAS' {FraContact: TFrame},
  ContactInterfaces in 'System\Contact\ContactInterfaces.pas',
  ContactManager in 'System\Contact\ContactManager.pas',
  ContactManagerInterfaces in 'System\Contact\ContactManagerInterfaces.pas',
  ContactSection in 'System\Contact\ContactSection.PAS',
  Containment in 'Element\Containment\Containment.pas',
  ContainmentDataAccess in 'Element\Containment\ContainmentDataAccess.PAS',
  ContainmentFrame in 'Element\Containment\ContainmentFrame.PAS' {FraContainment: TFrame},
  ContainmentInterfaces in 'Element\Containment\ContainmentInterfaces.pas',
  ContainmentSection in 'Element\Containment\ContainmentSection.PAS',
  Content in 'Element\Tracking\Content.pas',
  ContentDataAccess in 'Element\Tracking\ContentDataAccess.pas',
  ContentFrame in 'Element\Tracking\ContentFrame.PAS' {FraContent: TFrame},
  ContentInterfaces in 'Element\Tracking\ContentInterfaces.pas',
  ContentSection in 'Element\Tracking\ContentSection.PAS',
  Context in 'System\Context\Context.pas',
  ContextInterfaces in 'System\Context\ContextInterfaces.pas',
  Control in 'System\Control\Control.PAS',
  ControlDataAccess in 'System\Control\ControlDataAccess.PAS',
  ControlFrame in 'System\Control\ControlFrame.PAS' {FraControl: TFrame},
  ControlInterfaces in 'System\Control\ControlInterfaces.PAS',
  ControlIs in 'System\Control\ControlIs.PAS',
  ControlIsDataAccess in 'System\Control\ControlIsDataAccess.PAS',
  ControlIsFrame in 'System\Control\ControlIsFrame.PAS' {FraControlIs: TFrame},
  ControlIsInterfaces in 'System\Control\ControlIsInterfaces.PAS',
  ControlIsSection in 'System\Control\ControlIsSection.PAS',
  ControlSection in 'System\Control\ControlSection.PAS',
  ConversionManager in 'System\Conversion\ConversionManager.pas',
  ConversionManagerInterfaces in 'System\Conversion\ConversionManagerInterfaces.pas',
  CPUInterfaces in 'System\Configuration\CPUInterfaces.pas',
  cxcpu2kAMD in 'TP\CPU\cxCpu2kAMD.pas',
  cxcpu2kAPI in 'TP\CPU\cxCpu2kAPI.pas',
  cxcpu2kConst in 'TP\CPU\cxCpu2kConst.pas',
  cxCpu2kCyrix in 'TP\CPU\cxCpu2kCyrix.pas',
  cxcpu2kDefault in 'TP\CPU\cxCpu2kDefault.pas',
  cxCpu2kIDT in 'TP\CPU\cxCpu2kIDT.pas',
  cxcpu2kIntel in 'TP\CPU\cxCpu2kIntel.pas',
  cxCpu2kIntf in 'TP\CPU\cxCpu2kIntf.pas',
  cxCpu2kNexGen in 'TP\CPU\cxCpu2kNexGen.pas',
  cxCpu2kReg in 'TP\CPU\cxCpu2kReg.pas',
  cxCpu2kRise in 'TP\CPU\cxCpu2kRise.pas',
  cxCpu2kUMC in 'TP\CPU\cxCpu2kUMC.pas',
  cxCPU2kVcl in 'TP\CPU\cxCPU2kVcl.pas',
  cxVersionInfo in 'TP\CPU\cxVersionInfo.pas',
  daDOA in 'TP\Extra\daDOA.pas',
  DAInterfaces in 'System\Database\DAInterfaces.pas',
  DataAccess in 'System\Database\DataAccess.pas',
  DataAccessInterfaces in 'System\Database\DataAccessInterfaces.pas',
  Database in 'System\Database\Database.pas',
  DatabaseInterfaces in 'System\Database\DatabaseInterfaces.pas',
  DataInterfaces in 'System\Data\DataInterfaces.pas',
  DAUtilities in 'System\Database\DAUtilities.pas',
  DBConnection in 'System\Configuration\DBConnection.pas',
  DBConstants in 'System\Database\DBConstants.pas',
  DBContext in 'System\Database\DBContext.pas',
  DBHelper in 'System\Database\DBHelper.pas',
  DBQuery in 'System\Database\DBQuery.pas',
  DBSession in 'System\Database\DBSession.pas',
  DBStructure in 'System\Database\DBStructure.pas',
  DBTypes in 'System\Database\DBTypes.pas',
  DBUtilities in 'System\Database\DBUtilities.pas',
  dcdebug in 'TP\Dream\units\dcdebug.pas',
  dcfdes in 'TP\Dream\units\dcfdes.pas',
  debScreenEdit in 'System\Security\debScreenEdit.pas' {FrmdebScreenEdit},
  Debug in 'System\Error\debug.pas',
  Debugger in 'System\Debug\Debugger.pas',
  DebuggerHelper in 'System\Debug\DebuggerHelper.pas',
  DebuggerInterfaces in 'System\Debug\DebuggerInterfaces.pas',
  DebuggerTemplate in 'System\Debug\DebuggerTemplate.pas' {FrmDebugger},
  Decay in 'Module\Decay\Decay.pas',
  DialogsStd in 'System\Extension\DialogsStd.pas' {dmDialogs: TDataModule},
  Dimension in 'System\Dimension\Dimension.pas',
  DimensionBrowse in 'System\Dimension\DimensionBrowse.pas' {FrmDimensionBrowse},
  DimensionDataAccess in 'System\Dimension\DimensionDataAccess.pas',
  DimensionFrame in 'System\Dimension\DimensionFrame.pas' {FraDimension: TFrame},
  DimensionHelper in 'System\Dimension\DimensionHelper.pas',
  DimensionInterfaces in 'System\Dimension\DimensionInterfaces.pas',
  DimensionManager in 'System\Conversion\DimensionManager.pas',
  DimensionManagerInterfaces in 'System\Conversion\DimensionManagerInterfaces.pas',
  DimensionSection in 'System\Dimension\DimensionSection.pas',
  doaDatabaseInterfaces in 'System\Database\doa\doaDatabaseInterfaces.pas',
  doaDB in 'System\Database\doa\doaDB.pas',
  doaDBDataset in 'System\Database\doa\doaDBDataset.pas',
  doaDBQuery in 'System\Database\doa\doaDBQuery.pas',
  doaDBSession in 'System\Database\doa\doaDBSession.pas',
  doaDBTypes in 'System\Database\doa\doaDBTypes.pas',
  doaField in 'System\Database\doa\doaField.pas',
  doaParam in 'System\Database\doa\doaParam.pas',
  DummyCSIntf in 'System\Debug\CodeSite\DummyCSIntf.pas',
  dxDemoUtils in 'TP\dxGridStuff\dxDemoUtils.pas',
  dxEditUtils in 'TP\dxGridStuff\dxEditUtils.pas',
  dxGridMenus in 'TP\dxGridStuff\dxGridMenus.pas',
  EditModeControl in 'Utils\EditModeControl.pas',
  Element in 'Element\Element\Element.PAS',
  ElementDataAccess in 'Element\Element\ElementDataAccess.PAS',
  ElementFrame in 'Element\Element\ElementFrame.PAS' {FraElement: TFrame},
  ElementInterfaces in 'Element\Element\ElementInterfaces.PAS',
  ElementSection in 'Element\Element\ElementSection.PAS',
  Encryption in 'System\Encryption\Encryption.pas',
  EncryptionInterfaces in 'System\Encryption\EncryptionInterfaces.pas',
  Error in 'System\Error\Error.PAS',
  ErrorDataAccess in 'System\Error\ErrorDataAccess.PAS',
  ErrorFrame in 'System\Error\ErrorFrame.PAS' {FraError: TFrame},
  ErrorInterfaces in 'System\Error\ErrorInterfaces.PAS',
  ErrorSection in 'System\Error\ErrorSection.PAS',
  EventMonitor in 'System\Debug\Monitoring\EventMonitor.pas',
  Excel_TLB in 'TP\Office\Excel_TLB.pas',
  ExceptionDisplay in 'System\Error\ExceptionDisplay.pas' {FrmExceptionDisplay},
  Filter in 'System\Filter\Filter.pas',
  FilterInterfaces in 'System\Filter\FilterInterfaces.pas',
  Folder in 'Element\Report\Folder.pas',
  FolderDataAccess in 'Element\Report\FolderDataAccess.pas',
  FolderFrame in 'Element\Report\FolderFrame.PAS' {FraFolder: TFrame},
  FolderInterfaces in 'Element\Report\FolderInterfaces.pas',
  FolderSection in 'Element\Report\FolderSection.PAS',
  Format in 'System\Dimension\Format.pas',
  FormatBrowse in 'System\Dimension\FormatBrowse.pas',
  FormatDataAccess in 'System\Dimension\FormatDataAccess.pas',
  FormatFrame in 'System\Dimension\FormatFrame.pas' {FraFormat: TFrame},
  FormatInterfaces in 'System\Dimension\FormatInterfaces.pas',
  FormatSection in 'System\Dimension\FormatSection.pas',
  FormInterfaces in 'System\Extension\FormInterfaces.pas',
  FormMonitor in 'System\Debug\Monitoring\FormMonitor.pas',
  FormPrinter in 'Utils\FormPrinter.pas',
  Frame in 'Interface\Frame\Frame.pas' {FrameTemplate: TFrame},
  FrameInterfaces in 'Interface\Frame\FrameInterfaces.pas',
  FromDataAccess in 'Interface\Movement\FromDataAccess.pas',
  Grid in 'Interface\Grid\Grid.pas',
  GridManager in 'Interface\Grid\GridManager.pas',
  GridManagerInterfaces in 'Interface\Grid\GridManagerInterfaces.pas',
  HDInterfaces in 'System\Configuration\HDInterfaces.pas',
  Heirachy in 'System\Heirachy\Heirachy.pas',
  HeirachyHelper in 'System\Heirachy\HeirachyHelper.pas',
  HeirachyInterfaces in 'System\Heirachy\HeirachyInterfaces.pas',
  Icon in 'System\Icon\Icon.PAS',
  IconDataAccess in 'System\Icon\IconDataAccess.PAS',
  IconFrame in 'System\Icon\IconFrame.PAS' {FraIcon: TFrame},
  IconInterfaces in 'System\Icon\IconInterfaces.PAS',
  IconSection in 'System\Icon\IconSection.PAS',
  Icons in 'System\Icon\Icons.pas' {FrmIcons},
  ID in 'System\Heirachy\ID.pas',
  IDInterfaces in 'System\Heirachy\IDInterfaces.pas',
  Include in 'Element\Attribute\Include.PAS',
  IncludeDataAccess in 'Element\Attribute\IncludeDataAccess.PAS',
  IncludeFrame in 'Element\Attribute\IncludeFrame.PAS' {FraInclude: TFrame},
  IncludeInterfaces in 'Element\Attribute\IncludeInterfaces.PAS',
  IncludeSection in 'Element\Attribute\IncludeSection.PAS',
  IniDBConnection in 'System\Configuration\IniDBConnection.pas',
  InterfaceManager in 'Interface\InterfaceManager.pas',
  InterfaceManagerInterfaces in 'Interface\InterfaceManagerInterfaces.pas',
  InterfaceStack in 'UTILS\InterfaceStack.pas',
  InterfaceStore in 'Interface\InterfaceStore.pas',
  InterfaceStoreInterfaces in 'Interface\InterfaceStoreInterfaces.pas',
  IntoDataAccess in 'Interface\Movement\IntoDataAccess.pas',
  Isotope in 'Element\Isotope\Isotope.PAS',
  IsotopeDataAccess in 'Element\Isotope\IsotopeDataAccess.PAS',
  IsotopeFrame in 'Element\Isotope\IsotopeFrame.PAS' {FraIsotope: TFrame},
  IsotopeInterfaces in 'Element\Isotope\IsotopeInterfaces.PAS',
  IsotopeSection in 'Element\Isotope\IsotopeSection.PAS',
  Item in 'Element\Item\Item.pas',
  Item2 in 'Element\Item\Item2.pas',
  ItemDataAccess in 'Element\Item\ItemDataAccess.pas',
  ItemFrame in 'Element\Item\ItemFrame.pas' {fraItem: TFrame},
  ItemHistory in 'Element\Tracking\ItemHistory.pas',
  ItemHistoryDataAccess in 'Element\Tracking\ItemHistoryDataAccess.pas',
  ItemhIstoryFrame in 'Element\Tracking\ItemhIstoryFrame.PAS',
  ItemHistoryInterfaces in 'Element\Tracking\ItemHistoryInterfaces.pas',
  ItemhIstorySection in 'Element\Tracking\ItemhIstorySection.PAS',
  ItemHistoryTrackingDataAccess in 'Element\History\ItemHistoryTrackingDataAccess.pas',
  ItemInterfaces in 'Element\Item\ItemInterfaces.pas',
  ItemIs in 'Element\Item\ItemIs.pas',
  ItemIsAttributeIs in 'Element\Item\ItemIsAttributeIs.pas',
  ItemIsAttributeIsFrame in 'Element\Item\ItemIsAttributeIsFrame.pas' {FraItemIsAttributeIs: TFrame},
  ItemIsAttributeIsInterfaces in 'Element\Item\ItemIsAttributeIsInterfaces.pas',
  ItemIsAttributeIsSection in 'Element\Item\ItemIsAttributeIsSection.pas',
  ItemIsBrowse in 'Element\Item\ItemIsBrowse.pas',
  ItemIsDataAccess in 'Element\Item\ItemIsDataAccess.pas',
  ItemIsFrame in 'Element\Item\ItemIsFrame.pas' {FraItemIs: TFrame},
  ItemIsInterfaces in 'Element\Item\ItemIsInterfaces.pas',
  ItemIsSection in 'Element\Item\ItemIsSection.pas',
  ItemManager in 'Element\Item\ItemManager.pas',
  ItemManagerInterfaces in 'Element\Item\ItemManagerInterfaces.pas',
  ItemSection in 'Element\Item\ItemSection.pas',
  ItemReloaderDataAccess in 'Interface\Movement\ItemReloaderDataAccess.pas',
  ItemSelection in 'Element\Tracking\itemselection.pas' {FrmItemSelection},
  Itemsnapshot in 'Element\Item\Itemsnapshot.PAS',
  ItemsnapshotDataAccess in 'Element\Item\ItemsnapshotDataAccess.PAS',
  ItemsnapshotFrame in 'Element\Item\ItemsnapshotFrame.PAS' {FraItemsnapshot: TFrame},
  ItemsnapshotInterfaces in 'Element\Item\ItemsnapshotInterfaces.PAS',
  ItemsnapshotSection in 'Element\Item\ItemsnapshotSection.PAS',
  Join in 'Interface\View\Join.pas',
  Layout in 'System\Layout\Layout.pas',
  LayoutBrowseTemporary in 'System\Layout\LayoutBrowseTemporary.pas' {FrmLayoutBrowseTemporary},
  LayoutDataAccess in 'System\Layout\LayoutDataAccess.pas',
  LayoutFrame in 'System\Layout\LayoutFrame.PAS' {FraLayout: TFrame},
  LayoutInterfaces in 'System\Layout\LayoutInterfaces.pas',
  LayoutManager in 'System\Layout\LayoutManager.pas',
  LayoutSection in 'System\Layout\LayoutSection.PAS',
  LayoutView in 'System\Layout\LayoutView.pas',
  License in 'System\License\License.pas',
  LicenseDataAccess in 'System\License\LicenseDataAccess.pas',
  LicenseEx in 'System\License\LicenseEx.pas',
  LicenseExDataAccess in 'System\License\LicenseExDataAccess.pas',
  LicenseFrame in 'System\License\LicenseFrame.PAS' {FraLicense: TFrame},
  LicenseInterfaces in 'System\License\LicenseInterfaces.pas',
  Licenseoption in 'System\License\Licenseoption.PAS',
  LicenseoptionDataAccess in 'System\License\LicenseoptionDataAccess.PAS',
  LicenseoptionFrame in 'System\License\LicenseoptionFrame.PAS' {FraLicenseoption: TFrame},
  LicenseoptionInterfaces in 'System\License\LicenseoptionInterfaces.PAS',
  LicenseoptionSection in 'System\License\LicenseoptionSection.PAS',
  LicenseSection in 'System\License\LicenseSection.PAS',
  Limit in 'System\Limit\Limit.PAS',
  Limitapply in 'System\Limit\Limitapply.PAS',
  LimitapplyDataAccess in 'System\Limit\LimitapplyDataAccess.PAS',
  LimitapplyFrame in 'System\Limit\LimitapplyFrame.PAS' {FraLimitapply: TFrame},
  LimitapplyInterfaces in 'System\Limit\LimitapplyInterfaces.PAS',
  LimitapplySection in 'System\Limit\LimitapplySection.PAS',
  LimitDataAccess in 'System\Limit\LimitDataAccess.PAS',
  Limitevent in 'System\Limit\Limitevent.PAS',
  LimiteventDataAccess in 'System\Limit\LimiteventDataAccess.PAS',
  LimiteventFrame in 'System\Limit\LimiteventFrame.PAS' {FraLimitevent: TFrame},
  LimiteventInterfaces in 'System\Limit\LimiteventInterfaces.PAS',
  LimiteventSection in 'System\Limit\LimiteventSection.PAS',
  LimitFrame in 'System\Limit\LimitFrame.PAS' {FraLimit: TFrame},
  LimitInterfaces in 'System\Limit\LimitInterfaces.PAS',
  LimitSection in 'System\Limit\LimitSection.PAS',
  Linker in 'System\Linker\Linker.pas',
  LinkerInterfaces in 'System\Linker\LinkerInterfaces.pas',
  LinkerManager in 'System\Linker\LinkerManager.pas',
  LinkerManagerInterfaces in 'System\Linker\LinkerManagerInterfaces.pas',
  List in 'System\List\List.pas',
  ListHelper in 'System\List\ListHelper.pas',
  ListInterfaces in 'System\List\ListInterfaces.pas',
  ListUtilities in 'System\List\ListUtilities.pas',
  LL_VCL in 'TP\LL\ll_vcl.pas',
  LLApplication in 'System\Configuration\LLApplication.pas',
  LLCPU in 'System\Configuration\LLCPU.pas',
  llDebugger in 'System\Debug\llDebugger.pas',
  LLHD in 'System\Configuration\LLHD.pas',
  llHeirachy in 'System\llHeirachy.pas',
  LLNetwork in 'System\Configuration\LLNetwork.pas',
  LLOS in 'System\Configuration\LLOS.pas',
  LLOSEx in 'System\Configuration\LLOSEx.pas',
  LLRAM in 'System\Configuration\LLRAM.pas',
  llUtilities in 'System\Utilities\llUtilities.pas',
  llWinCRT in 'System\Debug\llWinCRT.pas',
  Loader in 'Interface\Selection\Loader.pas',
  Lob in 'System\LOB\Lob.pas',
  Locked in 'System\Locked\Locked.PAS',
  LockedDataAccess in 'System\Locked\LockedDataAccess.PAS',
  LockedFrame in 'System\Locked\LockedFrame.PAS' {FraLocked: TFrame},
  LockedInterfaces in 'System\Locked\LockedInterfaces.PAS',
  LockedSection in 'System\Locked\LockedSection.PAS',
  Locking in 'System\IdleOrBusy\Locking.pas' {FrmLocking},
  Logic in 'System\Logic\Logic.pas',
  LoginDataAccess in 'System\Login\LoginDataAccess.pas',
  LoginhIstory in 'System\Login\LoginhIstory.PAS',
  LoginhIstoryDataAccess in 'System\Login\LoginhIstoryDataAccess.PAS',
  LoginhIstoryFrame in 'System\Login\LoginhIstoryFrame.PAS' {FraLoginhIstory: TFrame},
  LoginhIstoryInterfaces in 'System\Login\LoginhIstoryInterfaces.PAS',
  LoginhIstorySection in 'System\Login\LoginhIstorySection.PAS',
  LoginManager in 'System\Login\LoginManager.pas',
  LoginManagerInterfaces in 'System\Login\LoginManagerInterfaces.pas',
  LoginNamesecurity in 'System\Login\Loginnamesecurity.PAS',
  LoginNamesecurityDataAccess in 'System\Login\LoginNamesecurityDataAccess.PAS',
  LoginNamesecurityFrame in 'System\Login\LoginNamesecurityFrame.PAS' {FraLoginNamesecurity: TFrame},
  LoginNamesecurityInterfaces in 'System\Login\LoginNamesecurityInterfaces.PAS',
  LoginNamesecuritySection in 'System\Login\LoginNamesecuritySection.PAS',
  Loginrecording in 'System\Login\Loginrecording.PAS',
  LoginrecordingDataAccess in 'System\Login\LoginrecordingDataAccess.PAS',
  LoginrecordingFrame in 'System\Login\LoginrecordingFrame.PAS' {FraLoginrecording: TFrame},
  LoginrecordingInterfaces in 'System\Login\LoginrecordingInterfaces.PAS',
  LoginrecordingSection in 'System\Login\LoginrecordingSection.PAS',
  Loginsecurity in 'System\Login\Loginsecurity.PAS',
  LoginsecurityDataAccess in 'System\Login\LoginsecurityDataAccess.PAS',
  LoginsecurityFrame in 'System\Login\LoginsecurityFrame.PAS' {FraLoginsecurity: TFrame},
  LoginsecurityInterfaces in 'System\Login\LoginsecurityInterfaces.PAS',
  LoginsecuritySection in 'System\Login\LoginsecuritySection.PAS',
  LogoutDataAccess in 'System\Operator\LogoutDataAccess.pas',
  Macro in 'System\Macro\Macro.pas',
  MacroDataAccess in 'System\Macro\MacroDataAccess.PAS',
  Macroelement in 'System\Macro\Macroelement.PAS',
  MacroelementDataAccess in 'System\Macro\MacroelementDataAccess.PAS',
  MacroelementFrame in 'System\Macro\MacroelementFrame.PAS' {FraMacroelement: TFrame},
  MacroelementInterfaces in 'System\Macro\MacroelementInterfaces.PAS',
  MacroelementSection in 'System\Macro\MacroelementSection.PAS',
  MacroFrame in 'System\Macro\MacroFrame.PAS' {FraMacro: TFrame},
  MacroHelper in 'System\Macro\MacroHelper.pas',
  MacroInterfaces in 'System\Macro\MacroInterfaces.pas',
  MacroManager in 'System\Macro\MacroManager.pas',
  MacroManagerInterfaces in 'System\Macro\MacroManagerInterfaces.pas',
  MacroSection in 'System\Macro\MacroSection.PAS',
  Manager in 'System\Manager\Manager.pas',
  ManagerInterfaces in 'System\Manager\ManagerInterfaces.pas',
  Manual in 'Interface\Movement\Manual.pas',
  ManualInterfaces in 'Interface\Movement\ManualInterfaces.pas',
  ManualRegister in 'Interface\Action\Register\ManualRegister.pas' {FrmManualRegister},
  MatchInterfaces in 'System\Match\MatchInterfaces.pas',
  Measure in 'System\Dimension\Measure.pas',
  MeasureBrowse in 'System\Dimension\MeasureBrowse.pas' {FrmMeasureBrowse},
  MeasureDataAccess in 'System\Dimension\MeasureDataAccess.pas',
  MeasureFrame in 'System\Dimension\measureframe.pas' {FraMeasure: TFrame},
  MeasureInterfaces in 'System\Dimension\MeasureInterfaces.pas',
  MeasureIs in 'System\Dimension\MeasureIs.pas',
  MeasureIsBrowse in 'System\Dimension\MeasureIsBrowse.pas' {FrmMeasureIsBrowse},
  MeasureIsDataAccess in 'System\Dimension\MeasureIsDataAccess.pas',
  MeasureIsFrame in 'System\Dimension\MeasureIsFrame.pas' {FraMeasureIs: TFrame},
  MeasureIsInterfaces in 'System\Dimension\MeasureIsInterfaces.pas',
  MeasureIsSection in 'System\Dimension\MeasureIsSection.pas',
  MeasureManager in 'System\Dimension\MeasureManager.pas',
  MeasureManagerInterfaces in 'System\Dimension\MeasureManagerInterfaces.pas',
  MeasureSection in 'System\Dimension\MeasureSection.pas',
  Menu in 'System\Menu\Menu.pas',
  MenuDataAccess in 'System\Menu\MenuDataAccess.pas',
  MenuInterfaces in 'System\Menu\MenuInterfaces.pas',
  MenuSecurity in 'System\Security\MenuSecurity.pas',
  Menutoolbar in 'System\Menu\Menutoolbar.PAS',
  MenutoolbarDataAccess in 'System\Menu\MenutoolbarDataAccess.PAS',
  MenutoolbarFrame in 'System\Menu\MenutoolbarFrame.PAS' {FraMenutoolbar: TFrame},
  MenutoolbarInterfaces in 'System\Menu\MenutoolbarInterfaces.PAS',
  MenutoolbarSection in 'System\Menu\MenutoolbarSection.PAS',
  MiscellaneousInterfaces in 'System\Miscellaneous\MiscellaneousInterfaces.pas',
  Module in 'System\Module\Module.pas',
  ModuleBrowse in 'System\Module\ModuleBrowse.pas' {FrmModuleBrowse},
  ModuleDataAccess in 'System\Module\ModuleDataAccess.PAS',
  ModuleEdit in 'System\Module\ModuleEdit.pas' {FrmModuleEdit},
  ModuleFrame in 'System\Module\ModuleFrame.PAS' {FraModule: TFrame},
  ModuleInterfaces in 'System\Module\ModuleInterfaces.pas',
  ModuleManager in 'System\Module\ModuleManager.pas',
  ModuleSection in 'System\Module\ModuleSection.PAS',
  ModuleValue in 'System\Module\ModuleValue.pas',
  Moreinfo in 'Main\MOREINFO.PAS' {FrmMoreInfo},
  Movement in 'Interface\Movement\Movement.pas',
  MovementDataAccess in 'Interface\Movement\MovementDataAccess.pas',
  MovementInterfaces in 'Interface\Movement\MovementInterfaces.pas',
  MovementManager in 'Interface\Movement\MovementManager.pas',
  MovementManagerInterfaces in 'Interface\Movement\MovementManagerInterfaces.pas',
  MovementStates in 'Interface\Movement\MovementStates.pas',
  MovementTo in 'Interface\Movement\MovementTo.pas',
  Multiplier in 'System\Dimension\Multiplier.pas',
  MultiplierBrowse in 'System\Dimension\MultiplierBrowse.pas',
  MultiplierDataAccess in 'System\Dimension\MultiplierDataAccess.pas',
  MultiplierFrame in 'System\Dimension\MultiplierFrame.pas' {FraMultiplier: TFrame},
  MultiplierInterfaces in 'System\Dimension\MultiplierInterfaces.pas',
  MultiplierSection in 'System\Dimension\MultiplierSection.pas',
  NetworkInterfaces in 'System\Configuration\NetworkInterfaces.pas',
  NewInstance in 'System\Configuration\NewInstance.pas' {FrmNewInstance},
  NewWorkStation in 'System\Configuration\Workstation\NewWorkStation.pas' {FrmNewWorkstation},
  Nexus in 'Main\Nexus\Nexus.pas',
  NexusHelper in 'Main\Nexus\NexusHelper.pas',
  NexusInterfaces in 'Main\Nexus\NexusInterfaces.pas',
  Notification in 'System\Notify\Notification.PAS',
  NotificationDataAccess in 'System\Notify\NotificationDataAccess.PAS',
  NotificationFrame in 'System\Notify\NotificationFrame.PAS' {FraNotification: TFrame},
  NotificationInterfaces in 'System\Notify\NotificationInterfaces.PAS',
  NotificationIs in 'System\Notify\NotificationIs.PAS',
  NotificationIsDataAccess in 'System\Notify\NotificationIsDataAccess.PAS',
  NotificationIsFrame in 'System\Notify\NotificationIsFrame.PAS' {FraNotificationIs: TFrame},
  NotificationIsInterfaces in 'System\Notify\NotificationIsInterfaces.PAS',
  NotificationIsSection in 'System\Notify\NotificationIsSection.PAS',
  NotificationSection in 'System\Notify\NotificationSection.PAS',
  Notify in 'System\Notify\Notify.PAS',
  NotifyDataAccess in 'System\Notify\NotifyDataAccess.PAS',
  NotifyFrame in 'System\Notify\NotifyFrame.PAS' {FraNotify: TFrame},
  NotifyInterfaces in 'System\Notify\NotifyInterfaces.pas',
  NotifySection in 'System\Notify\NotifySection.PAS',
  Null in 'Components\Null.pas',
  NullInterfaces in 'Components\NullInterfaces.pas',
  NumberUtilities in 'UTILS\NumberUtilities.pas',
  Observer in 'System\Observer\Observer.pas',
  ObserverInterfaces in 'System\Observer\ObserverInterfaces.pas',
  Office_TLB in 'TP\Office\Office_TLB.pas',
  Opener in 'Interface\Selection\Opener.pas',
  OpenerInterfaces in 'Interface\Selection\OpenerInterfaces.pas',
  Operator in 'System\Operator\Operator.pas',
  OperatorChangePassword in 'System\Operator\OperatorChangePassword.pas' {FrmOperatorChangePassword},
  OperatorDataAccess in 'System\Operator\OperatorDataAccess.pas',
  OperatorFrame in 'System\Operator\OperatorFrame.PAS' {FraOperator: TFrame},
  OperatorHelper in 'System\Operator\OperatorHelper.pas',
  OperatorInterfaces in 'System\Operator\OperatorInterfaces.pas',
  OperatorLogin in 'System\Operator\OperatorLogin.PAS' {FrmOperatorLogin},
  OperatorLogout in 'System\Operator\OperatorLogout.pas' {FrmOperatorLogout},
  OperatorMaintenance in 'System\Operator\OperatorMaintenance.pas' {FrmUserMaintenance},
  OperatorManager in 'System\Operator\OperatorManager.pas',
  OperatorManagerInterfaces in 'System\Operator\OperatorManagerInterfaces.pas',
  OperatorSection in 'System\Operator\OperatorSection.PAS',
  Operatorstatus in 'System\Operator\Operatorstatus.PAS',
  OperatorstatusDataAccess in 'System\Operator\OperatorstatusDataAccess.PAS',
  OperatorstatusFrame in 'System\Operator\OperatorstatusFrame.PAS' {FraOperatorstatus: TFrame},
  OperatorstatusInterfaces in 'System\Operator\OperatorstatusInterfaces.PAS',
  OperatorstatusSection in 'System\Operator\OperatorstatusSection.PAS',
  OSInterfaces in 'System\Configuration\OSInterfaces.pas',
  OSUtilities in 'Utils\OSUtilities.pas',
  Outstanding in 'System\Notify\Outstanding.PAS',
  OutstandingDataAccess in 'System\Notify\OutstandingDataAccess.PAS',
  OutstandingFrame in 'System\Notify\OutstandingFrame.PAS' {FraOutstanding: TFrame},
  OutstandingInterfaces in 'System\Notify\OutstandingInterfaces.PAS',
  OutstandingSection in 'System\Notify\OutstandingSection.PAS',
  Owner in 'System\Owner\Owner.pas',
  OwnerInterfaces in 'System\Owner\OwnerInterfaces.pas',
  PackageManager in 'System\Package\PackageManager.pas',
  PackageManagerInterfaces in 'System\Package\PackageManagerInterfaces.pas',
  Page in 'Element\Attribute\Page.PAS',
  PageDataAccess in 'Element\Attribute\PageDataAccess.PAS',
  PageFrame in 'Element\Attribute\PageFrame.PAS',
  PageInterfaces in 'Element\Attribute\PageInterfaces.PAS',
  PageSection in 'Element\Attribute\PageSection.PAS',
  Password in 'System\Password\Password.pas',
  PasswordHistory in 'System\Password\PasswordHistory.pas',
  PasswordHistoryDataAccess in 'System\Password\PasswordHistoryDataAccess.pas',
  PasswordhIstoryFrame in 'System\Password\PasswordhIstoryFrame.PAS',
  PasswordHistoryInterfaces in 'System\Password\PasswordHistoryInterfaces.pas',
  PasswordhIstorySection in 'System\Password\PasswordhIstorySection.PAS',
  Passwordsecurity in 'System\Password\Passwordsecurity.PAS',
  PasswordsecurityDataAccess in 'System\Password\PasswordsecurityDataAccess.PAS',
  PasswordsecurityFrame in 'System\Password\PasswordsecurityFrame.PAS' {FraPasswordsecurity: TFrame},
  PasswordsecurityInterfaces in 'System\Password\PasswordsecurityInterfaces.PAS',
  PasswordsecuritySection in 'System\Password\PasswordsecuritySection.PAS',
  PersistenceInterfaces in 'System\Persistence\PersistenceInterfaces.pas',
  ppMacro in 'Components\ppMacro.pas',
  ppMacro2 in 'Components\ppMacro2.pas',
  ppMacro3 in 'Components\ppMacro3.pas',
  Processing in 'Main\Background\Processing.pas',
  Product in 'System\Product\Product.PAS',
  ProductDataAccess in 'System\Product\ProductDataAccess.PAS',
  ProductFrame in 'System\Product\ProductFrame.PAS',
  ProductInterfaces in 'System\Product\ProductInterfaces.PAS',
  Productmodule in 'System\Product\Productmodule.PAS',
  ProductmoduleDataAccess in 'System\Product\ProductmoduleDataAccess.PAS',
  ProductmoduleFrame in 'System\Product\ProductmoduleFrame.PAS',
  ProductmoduleInterfaces in 'System\Product\ProductmoduleInterfaces.PAS',
  ProductmoduleSection in 'System\Product\ProductmoduleSection.PAS',
  ProductSection in 'System\Product\ProductSection.PAS',
  Progress in 'System\IdleOrBusy\Progress.pas',
  RAMInterfaces in 'System\Configuration\RAMInterfaces.pas',
  RBField in 'Element\Report\RBField.pas',
  RBJoin in 'Element\Report\RBJoin.pas',
  RBTable in 'Element\Report\RBTable.pas',
  ReferenceInterfaces in 'System\Reference\ReferenceInterfaces.pas',
  RegDBConnection in 'System\Configuration\RegDBConnection.pas',
  RegisterManager in 'Interface\Action\Register\RegisterManager.pas',
  RegisterManagerInterfaces in 'Interface\Action\Register\RegisterManagerInterfaces.pas',
  Report in 'Element\Report\Report.pas',
  ReportBrowse in 'Element\Report\ReportBrowse.pas' {FrmReportBrowse},
  ReportBuilderDataAccess in 'Element\Report\ReportBuilderDataAccess.pas',
  ReportDataAccess in 'Element\Report\ReportDataAccess.pas',
  ReportFrame in 'Element\Report\ReportFrame.PAS' {FraReport: TFrame},
  ReportInterface in 'Element\Report\ReportInterface.pas' {FrmReportInterface},
  ReportInterfaces in 'Element\Report\ReportInterfaces.pas',
  ReportManager in 'Element\Report\ReportManager.pas',
  ReportManagerInterfaces in 'Element\Report\ReportManagerInterfaces.pas',
  ReportSection in 'Element\Report\ReportSection.PAS',
  ReportPrint in 'Element\Report\ReportPrint.pas' {FrmReportPrint},
  ReportSelect in 'Element\Report\ReportSelect.pas' {FrmReportSelect},
  Saver in 'System\IdleOrBusy\Saver.pas',
  SaverInterfaces in 'System\IdleOrBusy\SaverInterfaces.pas',
  Schema in 'System\Schema\Schema.pas',
  SchemaColumn in 'System\Schema\SchemaColumn.pas',
  SchemaColumnDataAccess in 'System\Schema\SchemaColumnDataAccess.pas',
  SchemaColumnFrame in 'Interface\Schema\SchemaColumnFrame.pas' {FraSchemaColumn: TFrame},
  SchemaColumnInterfaces in 'System\Schema\SchemaColumnInterfaces.pas',
  SchemaColumnSection in 'Interface\Schema\SchemaColumnSection.pas',
  SchemaColumns in 'System\Schema\SchemaColumns.pas',
  SchemaConstraintFrame in 'Interface\Schema\SchemaConstraintFrame.pas' {FraSchemaConstraint: TFrame},
  SchemaConstraintSection in 'Interface\Schema\SchemaConstraintSection.pas',
  SchemaDataAccess in 'System\Schema\SchemaDataAccess.pas',
  SchemaHelper in 'System\Schema\SchemaHelper.pas',
  SchemaIndexFrame in 'Interface\Schema\SchemaIndexFrame.pas' {FraSchemaIndex: TFrame},
  SchemaIndexSection in 'Interface\Schema\SchemaIndexSection.pas',
  SchemaInterfaces in 'System\Schema\SchemaInterfaces.pas',
  SchemaKeyFrame in 'Interface\Schema\SchemaKeyFrame.pas' {FraSchemaKey: TFrame},
  SchemaKeySection in 'Interface\Schema\SchemaKeySection.pas',
  SchemaManager in 'System\Schema\SchemaManager.pas',
  SchemaManagerInterfaces in 'System\Schema\SchemaManagerInterfaces.pas',
  SchemaReferenceFrame in 'Interface\Schema\SchemaReferenceFrame.pas' {FraSchemaReference: TFrame},
  SchemaReferenceSection in 'Interface\Schema\SchemaReferenceSection.pas',
  SchemaSequenceFrame in 'Interface\Schema\SchemaSequenceFrame.pas' {FraSchemaSequence: TFrame},
  SchemaSequenceSection in 'Interface\Schema\SchemaSequenceSection.pas',
  SchemaSizes in 'System\Schema\SchemaSizes.pas',
  SchemaStore in 'Interface\Schema\SchemaStore.pas',
  SchemaStoreInterfaces in 'Interface\Schema\SchemaStoreInterfaces.pas',
  SchemaTable in 'System\Schema\SchemaTable.pas',
  SchemaTableDataAccess in 'System\Schema\SchemaTableDataAccess.pas',
  SchemaTableFrame in 'Interface\Schema\SchemaTableFrame.pas' {FraSchemaTable: TFrame},
  SchemaTableInterfaces in 'System\Schema\SchemaTableInterfaces.pas',
  SchemaTableSection in 'Interface\Schema\SchemaTableSection.pas',
  SchemaTables in 'System\Schema\SchemaTables.pas',
  SchemaUserFrame in 'Interface\Schema\SchemaUserFrame.pas' {FraSchemaUser: TFrame},
  SchemaUserSection in 'Interface\Schema\SchemaUserSection.pas',
  SchemaUtilities in 'System\Schema\SchemaUtilities.pas',
  SchemaValues in 'System\Schema\SchemaValues.pas',
  SchemaViewFrame in 'Interface\Schema\SchemaViewFrame.pas' {FraSchemaView: TFrame},
  SchemaViewSection in 'Interface\Schema\SchemaViewSection.pas',
  Screen in 'System\Screen\Screen.PAS',
  ScreenDataAccess in 'System\Screen\ScreenDataAccess.PAS',
  ScreenFrame in 'System\Screen\ScreenFrame.PAS' {FraScreen: TFrame},
  ScreenInterfaces in 'System\Screen\ScreenInterfaces.PAS',
  ScreenSection in 'System\Screen\ScreenSection.PAS',
  Security in 'System\Security\Security.PAS',
  SecurityDataAccess in 'System\Security\SecurityDataAccess.PAS',
  Securityevent in 'System\Security\Securityevent.PAS',
  SecurityeventDataAccess in 'System\Security\SecurityeventDataAccess.PAS',
  SecurityeventFrame in 'System\Security\SecurityeventFrame.PAS' {FraSecurityevent: TFrame},
  SecurityeventInterfaces in 'System\Security\SecurityeventInterfaces.PAS',
  SecurityeventSection in 'System\Security\SecurityeventSection.PAS',
  SecurityFrame in 'System\Security\SecurityFrame.PAS' {FraSecurity: TFrame},
  Securitygroup in 'System\Security\Securitygroup.PAS',
  SecuritygroupDataAccess in 'System\Security\SecuritygroupDataAccess.PAS',
  SecuritygroupFrame in 'System\Security\SecuritygroupFrame.PAS' {FraSecuritygroup: TFrame},
  SecuritygroupInterfaces in 'System\Security\SecuritygroupInterfaces.PAS',
  SecuritygroupSection in 'System\Security\SecuritygroupSection.PAS',
  SecurityInterfaces in 'System\Security\SecurityInterfaces.PAS',
  SecurityManager in 'System\Security\SecurityManager.pas',
  SecurityManagerInterfaces in 'System\Security\SecurityManagerInterfaces.pas',
  Securitymember in 'System\Security\Securitymember.PAS',
  SecuritymemberDataAccess in 'System\Security\SecuritymemberDataAccess.PAS',
  SecuritymemberFrame in 'System\Security\SecuritymemberFrame.PAS' {FraSecuritymember: TFrame},
  SecuritymemberInterfaces in 'System\Security\SecuritymemberInterfaces.PAS',
  SecuritymemberSection in 'System\Security\SecuritymemberSection.PAS',
  SecurityOptionEdit in 'System\Security\SecurityOptionEdit.pas' {FrmSecurityOptionEdit},
  SecuritySection in 'System\Security\SecuritySection.PAS',
  SelectionManager in 'Interface\Selection\SelectionManager.pas',
  SelectionManagerInterfaces in 'Interface\Selection\SelectionManagerInterfaces.pas',
  Sequencer in 'System\IdleOrBusy\Sequencer.pas',
  SessionControl in 'System\Operator\SessionControl.pas' {FrmSessionControl},
  SetupImplementations in 'Main\SetupImplementations.pas',
  SetupInterfaces in 'Main\SetupInterfaces.pas',
  SetupMain in 'Main\SetupMain.pas' {FrmSetupMain},
  Shares in 'System\Share\Shares.pas',
  Splash in 'Main\Splash\Splash.pas' {FrmSplash},
  SplashHelper in 'Main\Splash\SplashHelper.pas',
  SplashInterfaces in 'Main\Splash\SplashInterfaces.pas',
  SQL in 'System\Database\SQL.pas',
  SQLInterfaces in 'System\Database\SQLInterfaces.pas',
  StateMachine in 'Pattern\StateMachine.pas',
  StateMachineInterfaces in 'Pattern\StateMachineInterfaces.pas',
  Status in 'Element\Status\Status.PAS',
  StatusBarManager in 'System\Status\StatusBarManager.pas',
  StatusBarManagerInterfaces in 'System\Status\StatusBarManagerInterfaces.pas',
  StatusDataAccess in 'Element\Status\StatusDataAccess.PAS',
  StatusFrame in 'Element\Status\StatusFrame.PAS',
  StatusInterfaces in 'Element\Status\StatusInterfaces.PAS',
  StatusIs in 'Element\Status\StatusIs.PAS',
  StatusIsDataAccess in 'Element\Status\StatusIsDataAccess.PAS',
  StatusIsFrame in 'Element\Status\StatusIsFrame.PAS',
  StatusIsInterfaces in 'Element\Status\StatusIsInterfaces.PAS',
  StatusIsSection in 'Element\Status\StatusIsSection.PAS',
  StatusSection in 'Element\Status\StatusSection.PAS',
  StComObjEx in 'System\Extension\StComObjEx.pas',
  StConstants in 'System\Globals\StConstants.pas',
  StDialogsEx in 'System\Extension\StDialogsEx.pas',
  StEvents in 'System\Event\StEvents.pas',
  StExceptions in 'System\Error\StExceptions.pas',
  StFormsEx in 'System\Extension\StFormsEx.pas',
  Sticker in 'Element\Sticker\Sticker.pas',
  StickerBrowse in 'Element\Sticker\StickerBrowse.pas' {FrmStickerBrowse},
  StickerExplorer in 'Element\Sticker\StickerExplorer.pas' {FrmStickerExplorer},
  StickerFolder in 'Element\Sticker\StickerFolder.pas',
  StickerFolderInterfaces in 'Element\Sticker\StickerFolderInterfaces.pas',
  StickerInterfaces in 'Element\Sticker\StickerInterfaces.pas',
  StickerManager in 'Element\Sticker\StickerManager.pas',
  StickerManagerInterfaces in 'Element\Sticker\StickerManagerInterfaces.pas',
  StickerPrint in 'Element\Sticker\StickerPrint.pas' {FrmStickerPrint},
  StickerSelect in 'Element\Sticker\StickerSelect.pas' {FrmStickerSelect},
  StInterfaceList in 'System\Extension\StInterfaceList.pas',
  StkTrace in 'System\Error\STKTRACE.PAS',
  StMacros in 'System\Macro\StMacros.pas',
  Store in 'System\Thing\Store.pas',
  StoreInterfaces in 'System\Thing\StoreInterfaces.pas',
  Structure in 'Element\Tree\Structure.pas',
  StructureDataAccess in 'Element\Tree\StructureDataAccess.pas',
  StructureFrame in 'Element\Tree\StructureFrame.PAS' {FraStructure: TFrame},
  StructureHelper in 'Element\Tree\StructureHelper.pas',
  StructureInterfaces in 'Element\Tree\StructureInterfaces.pas',
  StructureManager in 'Element\Tree\StructureManager.pas',
  StructureManagerInterfaces in 'Element\Tree\StructureManagerInterfaces.pas',
  StructureSection in 'Element\Tree\StructureSection.PAS',
  StTypes in 'System\Globals\StTypes.pas',
  Study in 'Element\study\Study.PAS',
  StudyDataAccess in 'Element\study\StudyDataAccess.PAS',
  StudyFrame in 'Element\study\StudyFrame.PAS' {FraStudy: TFrame},
  StudyInterfaces in 'Element\study\StudyInterfaces.PAS',
  StudyIs in 'Element\study\StudyIs.PAS',
  StudyIsDataAccess in 'Element\study\StudyIsDataAccess.PAS',
  StudyIsFrame in 'Element\study\StudyIsFrame.PAS' {FraStudyIs: TFrame},
  StudyIsInterfaces in 'Element\study\StudyIsInterfaces.PAS',
  StudyIsSection in 'Element\study\StudyIsSection.PAS',
  StudySection in 'Element\study\StudySection.PAS',
  Tag in 'System\Tag\Tag.pas',
  Template in 'Interface\Frame\Template.pas' {FrameTemplate1: TFrame},
  Thing in 'System\Thing\Thing.pas',
  ThingHelper in 'System\Thing\ThingHelper.pas',
  ThingInterfaces in 'System\Thing\ThingInterfaces.pas',
  ThingTypes in 'System\Thing\ThingTypes.pas',
  ThreadSafeObjectQueue in 'System\Error\ThreadSafeObjectQueue.pas',
  Ticker in 'System\Ticker\Ticker.pas',
  TickerInterfaces in 'System\Ticker\TickerInterfaces.pas',
  TimoutLocking in 'System\IdleOrBusy\TimoutLocking.pas' {FrmLock},
  TraceDebugger in 'System\Debug\TraceDebugger.pas',
  Tracer in 'System\Debug\Monitoring\Tracer.pas',
  Transaction in 'Element\Transaction\Transaction.pas',
  Transaction2 in 'Element\Transaction\Transaction2.pas',
  TransactionCreate in 'Element\Transaction\TransactionCreate.pas' {FrmTransactionCreate},
  TransactionDataAccess in 'Element\Transaction\TransactionDataAccess.pas',
  TransactionFrame in 'Element\Transaction\TransactionFrame.pas' {fraTransaction: TFrame},
  TransactionInterfaces in 'Element\Transaction\TransactionInterfaces.pas',
  TransactionIs in 'Element\Transaction\Transactionis.pas',
  TransactionIsBrowse in 'Element\Transaction\TransactionIsBrowse.pas',
  TransactionIsDataAccess in 'Element\Transaction\transactionisDataAccess.pas',
  TransactionIsFrame in 'Element\Transaction\TransactionIsFrame.pas' {FraTransactionIs: TFrame},
  TransactionIsInterfaces in 'Element\Transaction\TransactionIsInterfaces.pas',
  TransactionIsSection in 'Element\Transaction\TransactionIsSection.pas',
  TransactionIsTypes in 'Element\Transaction\TransactionIsTypes.pas',
  TransactionManager in 'Element\Transaction\TransactionManager.pas',
  TransactionManagerInterfaces in 'Element\Transaction\TransactionManagerInterfaces.pas',
  TransactionSection in 'Element\Transaction\TransactionSection.pas',
  Tree in 'Element\Tree\Tree.pas',
  TreeDataAccess in 'Element\Tree\TreeDataAccess.pas',
  TreeInterfaces in 'Element\Tree\TreeInterfaces.pas',
  TriggerManager in 'System\Trigger\TriggerManager.pas',
  TriggerManagerInterfaces in 'System\Trigger\TriggerManagerInterfaces.pas',
  Troolean in 'System\Troolean\Troolean.pas',
  Twofish in 'Components\TWOFISH.PAS',
  TXComp in 'TP\Extra\TXCOMP.pas',
  TXParse in 'TP\extra\TXPARSE.pas',
  TXTIFF in 'TP\Extra\TXTIFF.pas',
  TXtraDev in 'TP\extra\TxtraDev.pas',
  ValidationEdit in 'System\License\ValidationEdit.pas' {FrmValidationEdit},
  Value in 'System\Conversion\Value.pas',
  ValueInterfaces in 'System\Conversion\ValueInterfaces.pas',
  ValueManager in 'System\Conversion\ValueManager.pas',
  ValueManagerInterfaces in 'System\Conversion\ValueManagerInterfaces.pas',
  Variable in 'System\Variable\Variable.pas',
  VBIDE_TLB in 'TP\Office\VBIDE_TLB.pas',
  VersionInterfaces in 'System\Version\VersionInterfaces.pas',
  View in 'Interface\View\View.pas',
  ViewManager in 'Interface\View\ViewManager.pas',
  ViewManagerInterfaces in 'Interface\View\ViewManagerInterfaces.pas',
  Wait in 'System\IdleOrBusy\WAIT.PAS' {FrmWait},
  WaitInterfaces in 'System\IdleOrBusy\WaitInterfaces.pas',
  WinCRT in 'System\Debug\WinCRT.pas',
  WinCRTDebugger in 'System\Debug\WinCRTDebugger.pas' {fraDebugWinCRTFrame: TFrame},
  WinCRTInterfaces in 'System\Debug\WinCRTInterfaces.pas',
  WindowsEx in 'System\Extension\WindowsEx.pas',
  Wizard in 'Interface\Wizard\Wizard.pas',
  BookHelper in 'Interface\book\BookHelper.pas',
  WizardInterfaces in 'Interface\Wizard\WizardInterfaces.pas',
  WizardManager in 'Interface\Wizard\WizardManager.pas',
  WizardManagerInterfaces in 'Interface\Wizard\WizardManagerInterfaces.pas',
  WizardTemplate in 'Interface\Wizard\WizardTemplate.pas' {frmWizardTemplate},
  WizardToForm in 'Interface\Wizard\WizardToForm.pas',
  WizardToFormInterfaces in 'Interface\Wizard\WizardToFormInterfaces.pas',
  Word_TLB in 'TP\Office\Word_TLB.pas',
  Workstation in 'System\Configuration\Workstation\Workstation.pas',
  WorkstationDataAccess in 'System\Configuration\Workstation\WorkstationDataAccess.pas',
  WorkstationFrame in 'System\Configuration\Workstation\WorkstationFrame.PAS' {FraWorkstation: TFrame},
  WorkstationInterfaces in 'System\Configuration\Workstation\WorkstationInterfaces.pas',
  WorkstationManager in 'System\Configuration\Workstation\WorkstationManager.pas',
  WorkstationManagerInterfaces in 'System\Configuration\Workstation\WorkstationManagerInterfaces.pas',
  WorkstationSection in 'System\Configuration\Workstation\WorkstationSection.PAS',
  SelectionManagerDataAccess in 'Interface\Selection\SelectionManagerDataAccess.pas',
  PasswordSecurityTypes in 'System\Password\PasswordSecurityTypes.pas',
  LoginRecordingTypes in 'System\Login\LoginRecordingTypes.pas',
  LoginSecurityTypes in 'System\Login\LoginSecurityTypes.pas',
  AttributeIsTypes in 'Element\Attribute\AttributeIsTypes.pas',
  DefaultBrowse in 'Interface\Browse\DefaultBrowse.pas',
  DefaultBrowseInterfaces in 'Interface\Browse\DefaultBrowseInterfaces.pas',
  ContactIs in 'System\Contact\ContactIs.PAS',
  ContactIsDataAccess in 'System\Contact\ContactIsDataAccess.PAS',
  ContactIsFrame in 'System\Contact\ContactIsFrame.PAS' {FraContactIs: TFrame},
  ContactIsInterfaces in 'System\Contact\ContactIsInterfaces.PAS',
  ContactIsSection in 'System\Contact\ContactIsSection.PAS',
  AuditManager in 'System\Audit\AuditManager.pas',
  AuditManagerDataAccess in 'System\Audit\AuditManagerDataAccess.pas',
  AuditManagerDataAccessInterfaces in 'System\Audit\AuditManagerDataAccessInterfaces.pas',
  AuditManagerInterfaces in 'System\Audit\AuditManagerInterfaces.pas',
  llObject in 'Components\llObject.pas',
  LoginInterfaces in 'System\Login\LoginInterfaces.pas',
  EditInterfaces in 'Interface\Edit\EditInterfaces.pas',
  Edit in 'Interface\Edit\Edit.pas',
  EditTemplate in 'Interface\Edit\EditTemplate.pas' {FrmEditTemplate},
  Editee in 'Interface\Edit\Editee.pas',
  SelectTemplate in 'Interface\Select\SelectTemplate.pas' {FrmSelectTemplate},
  Select in 'Interface\Select\Select.pas',
  SelectInterfaces in 'Interface\Select\SelectInterfaces.pas',
  ScreenManager in 'System\Screen\ScreenManager.pas',
  ScreenManagerInterfaces in 'System\Screen\ScreenManagerInterfaces.pas',
  CompoundManager in 'Element\Compound\CompoundManager.pas',
  CompoundManagerInterfaces in 'Element\Compound\CompoundManagerInterfaces.pas',
  IsotopeManager in 'Element\Isotope\IsotopeManager.pas',
  IsotopeManagerInterfaces in 'Element\Isotope\IsotopeManagerInterfaces.pas',
  ElementManagerInterfaces in 'Element\Element\ElementManagerInterfaces.pas',
  ElementManager in 'Element\Element\ElementManager.pas',
  StatusManager in 'Element\Status\StatusManager.pas',
  StatusManagerInterfaces in 'Element\Status\StatusManagerInterfaces.pas',
  AssociateManager in 'Element\Associate\AssociateManager.pas',
  AssociateManagerInterfaces in 'Element\Associate\AssociateManagerInterfaces.pas',
  DefaultBookInterfaces in 'Interface\book\DefaultBookInterfaces.pas',
  BCS in 'Interface\book\BCS.pas',
  BCSInterfaces in 'Interface\book\BCSInterfaces.pas',
  Book in 'Interface\book\Book.pas',
  BookInterfaces in 'Interface\book\BookInterfaces.pas',
  DefaultBook in 'Interface\book\DefaultBook.pas',
  DefaultChapterInterfaces in 'Interface\Chapter\DefaultChapterInterfaces.pas',
  Chapter in 'Interface\Chapter\Chapter.pas',
  ChapterInterfaces in 'Interface\Chapter\ChapterInterfaces.pas',
  DefaultChapter in 'Interface\Chapter\DefaultChapter.pas',
  SectionInterfaces in 'Interface\section\SectionInterfaces.pas',
  Section in 'Interface\section\Section.pas',
  FrameHelper in 'Interface\Frame\FrameHelper.pas',
  ItemSectionInterfaces in 'Element\Item\ItemSectionInterfaces.pas',
  WizardFinishFrame in 'Interface\Wizard\WizardFinishFrame.pas' {fraWizardFinish: TFrame},
  WizardFinishSection in 'Interface\Wizard\WizardFinishSection.pas',
  WizardStartFrame in 'Interface\Wizard\WizardStartFrame.pas' {fraWizardStart: TFrame},
  WizardStartSection in 'Interface\Wizard\WizardStartSection.pas',
  LoginHistoryTypes in 'System\Login\LoginHistoryTypes.pas';

{$R *.RES}

begin
  Application.ShowMainForm := False;
  Application.CreateForm(TFrmSetupMain, FrmSetupMain);
  Application.Initialize;
  Application.Run;
{$IFDEF DontCompile}
  don't compile!
{$ENDIF}
end.
