(*****************************************************************************
  Program:     Stacy
  Authors:     Lablogic
******************************************************************************)

program Stacy;

{%ToDo 'Stacy.todo'}

uses
  Forms,
  Windows,
  Classes,
  ExtCtrls,
  StdCtrls,
  SysUtils,
  CodeSite in 'System\Debug\CodeSite\CodeSite.pas' {FrmCodeSite},
  Boot in 'System\Boot\Boot.pas',
  llCache in 'System\llCache.pas',
  ObserverInterfaces in 'System\Observer\ObserverInterfaces.pas',
  Observer in 'System\Observer\Observer.pas',
  NexusInterfaces in 'Main\Nexus\NexusInterfaces.pas',
  Nexus in 'Main\Nexus\Nexus.pas',
  Heirachy in 'System\Heirachy\Heirachy.pas',
  StFormsEx in 'System\Extension\StFormsEx.pas',
  StDialogsEx in 'System\Extension\StDialogsEx.pas',
  StacyMain in 'Main\StacyMain.pas' {FrmStacyMain},
  Icons in 'System\Icon\Icons.pas' {FrmIcons},
  StConstants in 'System\Globals\StConstants.pas',
  FormMonitor in 'System\Debug\Monitoring\FormMonitor.pas',
  Tracer in 'System\Debug\Monitoring\Tracer.pas',
  Progress in 'System\IdleOrBusy\Progress.pas',
  Check in 'Utils\Check.pas',
  WindowsEx in 'System\Extension\WindowsEx.pas',
  LicenseExDataAccess in 'System\License\LicenseExDataAccess.pas',
  Locking in 'System\IdleOrBusy\Locking.pas' {FrmLocking},
  Advertiser_TLB in 'System\IdleOrBusy\Advertiser_TLB.pas',
  Sequencer in 'System\IdleOrBusy\Sequencer.pas',
  Saver in 'System\IdleOrBusy\Saver.pas',
  TimoutLocking in 'System\IdleOrBusy\TimoutLocking.pas' {FrmLock},
  FormPrinter in 'Utils\FormPrinter.pas',
  ExceptionDisplay in 'System\Error\ExceptionDisplay.pas' {FrmExceptionDisplay},
  AEPostStartup in 'System\Startup\AEPostStartup.pas',
  AEPreConnect in 'System\Startup\AEPreConnect.pas',
  AEConnect in 'System\Startup\AEConnect.pas',
  AEPostConnect in 'System\Startup\AEPostConnect.pas',
  AEPreUpgrade in 'System\Startup\AEPreUpgrade.pas',
  AEUpgrade in 'System\Startup\AEUpgrade.pas',
  AEPostUpgrade in 'System\Startup\AEPostUpgrade.pas',
  AEPreReadyToGo in 'System\Startup\AEPreReadyToGo.pas',
  AEReadyToGo in 'System\Startup\AEReadyToGo.pas',
  AEPostReadyToGo in 'System\Startup\AEPostReadyToGo.pas',
  AEPostForceUserLogout in 'System\Startup\AEPostForceUserLogout.pas',
  Splash in 'Main\Splash\Splash.pas' {FrmSplash},
  AEForceUserLogout in 'System\Startup\AEForceUserLogout.pas',
  AEPreForceUserLogout in 'System\Startup\AEPreForceUserLogout.pas',
  AEPreStartup in 'System\Startup\AEPreStartup.pas',
  AEStartup in 'System\Startup\AEStartup.pas',
  Ticker in 'System\Ticker\Ticker.pas',
  Clock in 'System\Clock\Clock.pas',
  Configuration in 'System\Configuration\Configuration.pas',
  DBTypes in 'System\Database\DBTypes.pas',
  DBConstants in 'System\Database\DBConstants.pas',
  DBContext in 'System\Database\DBContext.pas',
  DBQuery in 'System\Database\DBQuery.pas',
  DBSession in 'System\Database\DBSession.pas',
  DBStructure in 'System\Database\DBStructure.pas',
  StTypes in 'System\Globals\StTypes.pas',
  cLLVersionInfo in 'Components\cLLVersionInfo.pas',
  LLApplication in 'System\Configuration\LLApplication.pas',
  IniDBConnection in 'System\Configuration\IniDBConnection.pas',
  DBConnection in 'System\Configuration\DBConnection.pas',
  RegDBConnection in 'System\Configuration\RegDBConnection.pas',
  NewInstance in 'System\Configuration\NewInstance.pas' {FrmNewInstance},
  bdeOracleDBTypes in 'System\Database\bdeOracle\bdeOracleDBTypes.pas',
  bdeOracleDBQuery in 'System\Database\bdeOracle\bdeOracleDBQuery.pas',
  bdeOracleDBSession in 'System\Database\bdeOracle\bdeOracleDBSession.pas',
  bdeOracleDB in 'System\Database\bdeOracle\bdeOracleDB.pas',
  bdeStandardDBTypes in 'System\Database\bdestandard\bdeStandardDBTypes.pas',
  bdeStandardDBQuery in 'System\Database\bdestandard\bdeStandardDBQuery.pas',
  bdeStandardDBSession in 'System\Database\bdestandard\bdeStandardDBSession.pas',
  bdeStandardDB in 'System\Database\bdestandard\bdeStandardDB.pas',
  doaDBTypes in 'System\Database\doa\doaDBTypes.pas',
  doaDBDataset in 'System\Database\doa\doaDBDataset.pas',
  doaDBSession in 'System\Database\doa\doaDBSession.pas',
  doaDB in 'System\Database\doa\doaDB.pas',
  Encryption in 'System\Encryption\Encryption.pas',
  Twofish in 'Components\TWOFISH.PAS',
  LicenseEx in 'System\License\LicenseEx.pas',
  About in 'Main\ABOUT.PAS' {FrmAbout},
  Moreinfo in 'Main\MOREINFO.PAS' {FrmMoreInfo},
  Backdoor in 'System\Security\Backdoor.PAS' {FrmBackDoor},
  OperatorMaintenance in 'System\Operator\OperatorMaintenance.pas' {FrmUserMaintenance},
  OperatorInterfaces in 'System\Operator\OperatorInterfaces.pas',
  Operator in 'System\Operator\Operator.pas',
  OperatorDataAccess in 'System\Operator\OperatorDataAccess.pas',
  Password in 'System\Password\Password.pas',
  DBUtilities in 'System\Database\DBUtilities.pas',
  SecurityManager in 'System\Security\SecurityManager.pas',
  ClockDataAccess in 'System\Clock\ClockDataAccess.pas',
  BackdoorDataAccess in 'System\Security\BackdoorDataAccess.pas',
  ContainmentInterfaces in 'Element\Containment\ContainmentInterfaces.pas',
  Containment in 'Element\Containment\Containment.pas',
  OperatorLogin in 'System\Operator\OperatorLogin.PAS' {FrmOperatorLogin},
  LoginDataAccess in 'System\Login\LoginDataAccess.pas',
  SessionControl in 'System\Operator\SessionControl.pas' {FrmSessionControl},
  OperatorChangePassword in 'System\Operator\OperatorChangePassword.pas' {FrmOperatorChangePassword},
  OperatorLogout in 'System\Operator\OperatorLogout.pas' {FrmOperatorLogout},
  LogoutDataAccess in 'System\Operator\LogoutDataAccess.pas',
  DialogsStd in 'System\Extension\DialogsStd.pas' {dmDialogs: TDataModule},
  Clipboard in 'System\Clipboard\Clipboard.pas',
  CollectionBrowse in 'Element\Collection\CollectionBrowse.pas' {FrmCollectionBrowse},
  WorkstationDataAccess in 'System\Configuration\Workstation\WorkstationDataAccess.pas',
  StatusBarManager in 'System\Status\StatusBarManager.pas',
  Wait in 'System\IdleOrBusy\WAIT.PAS' {FrmWait},
  Grid in 'Interface\Grid\Grid.pas',
  ItemInterfaces in 'Element\Item\ItemInterfaces.pas',
  Item in 'Element\Item\Item.pas',
  ItemDataAccess in 'Element\Item\ItemDataAccess.pas',
  MacroInterfaces in 'System\Macro\MacroInterfaces.pas',
  Macro in 'System\Macro\Macro.pas',
  ItemHistoryInterfaces in 'Element\Tracking\ItemHistoryInterfaces.pas',
  ItemHistory in 'Element\Tracking\ItemHistory.pas',
  ItemHistoryDataAccess in 'Element\Tracking\ItemHistoryDataAccess.pas',
  WorkstationInterfaces in 'System\Configuration\Workstation\WorkstationInterfaces.pas',
  Workstation in 'System\Configuration\Workstation\Workstation.pas',
  LLCPU in 'System\Configuration\LLCPU.pas',
  cxVersionInfo in 'TP\CPU\cxVersionInfo.pas',
  cxcpu2kAPI in 'TP\CPU\cxCpu2kAPI.pas',
  cxcpu2kConst in 'TP\CPU\cxCpu2kConst.pas',
  cxCpu2kCyrix in 'TP\CPU\cxCpu2kCyrix.pas',
  cxcpu2kDefault in 'TP\CPU\cxCpu2kDefault.pas',
  cxCpu2kIDT in 'TP\CPU\cxCpu2kIDT.pas',
  cxcpu2kIntel in 'TP\CPU\cxCpu2kIntel.pas',
  cxCpu2kIntf in 'TP\CPU\cxCpu2kIntf.pas',
  cxCpu2kNexGen in 'TP\CPU\cxCpu2kNexGen.pas',
  cxCpu2kReg in 'TP\CPU\cxCpu2kReg.pas',
  cxCpu2kRise in 'TP\CPU\cxCpu2kRise.pas',
  cxCpu2kUMC in 'TP\CPU\cxCpu2kUMC.pas',
  cxCPU2kVcl in 'TP\CPU\cxCPU2kVcl.pas',
  cxcpu2kAMD in 'TP\CPU\cxCpu2kAMD.pas',
  LLOS in 'System\Configuration\LLOS.pas',
  LLHD in 'System\Configuration\LLHD.pas',
  LLRAM in 'System\Configuration\LLRAM.pas',
  LLOSEx in 'System\Configuration\LLOSEx.pas',
  LLNetwork in 'System\Configuration\LLNetwork.pas',
  OSUtilities in 'Utils\OSUtilities.pas',
  ValidationEdit in 'System\License\ValidationEdit.pas' {FrmValidationEdit},
  NewWorkStation in 'System\Configuration\Workstation\NewWorkStation.pas' {FrmNewWorkstation},
  Processing in 'Main\Background\Processing.pas',
  Decay in 'Module\Decay\Decay.pas',
  DataAccessInterfaces in 'System\Database\DataAccessInterfaces.pas',
  LicenseInterfaces in 'System\License\LicenseInterfaces.pas',
  License in 'System\License\License.pas',
  LicenseDataAccess in 'System\License\LicenseDataAccess.pas',
  ModuleInterfaces in 'System\Module\ModuleInterfaces.pas',
  Module in 'System\Module\Module.pas',
  PasswordHistoryInterfaces in 'System\Password\PasswordHistoryInterfaces.pas',
  PasswordHistory in 'System\Password\PasswordHistory.pas',
  PasswordHistoryDataAccess in 'System\Password\PasswordHistoryDataAccess.pas',
  CollectionInterfaces in 'Element\Collection\CollectionInterfaces.pas',
  Collection in 'Element\Collection\Collection.pas',
  CollectionDataAccess in 'Element\Collection\CollectionDataAccess.pas',
  TransactionInterfaces in 'Element\Transaction\TransactionInterfaces.pas',
  Transaction in 'Element\Transaction\Transaction.pas',
  TransactionDataAccess in 'Element\Transaction\TransactionDataAccess.pas',
  ContentInterfaces in 'Element\Tracking\ContentInterfaces.pas',
  Content in 'Element\Tracking\Content.pas',
  ContentDataAccess in 'Element\Tracking\ContentDataAccess.pas',
  StructureInterfaces in 'Element\Tree\StructureInterfaces.pas',
  Structure in 'Element\Tree\Structure.pas',
  StructureDataAccess in 'Element\Tree\StructureDataAccess.pas',
  TreeInterfaces in 'Element\Tree\TreeInterfaces.pas',
  Tree in 'Element\Tree\Tree.pas',
  TreeDataAccess in 'Element\Tree\TreeDataAccess.pas',
  SelectionManager in 'Interface\Selection\SelectionManager.pas',
  ItemHistoryTrackingDataAccess in 'Element\History\ItemHistoryTrackingDataAccess.pas',
  cLLComboBoxs in 'Components\cLLComboBoxs.pas',
  cLLComboBox in 'Components\cLLComboBox.pas',
  GridManager in 'Interface\Grid\GridManager.pas',
  View in 'Interface\View\View.pas',
  Join in 'Interface\View\Join.pas',
  doaDBQuery in 'System\Database\doa\doaDBQuery.pas',
  doaField in 'System\Database\doa\doaField.pas',
  doaParam in 'System\Database\doa\doaParam.pas',
  EditModeControl in 'Utils\EditModeControl.pas',
  dcfdes in 'TP\Dream\units\dcfdes.pas',
  dcdebug in 'TP\Dream\units\dcdebug.pas',
  Barcode in 'System\Barcode\BARCODE.PAS',
  LL_VCL in 'TP\LL\ll_vcl.pas',
  CMBTL5 in 'TP\LL\Cmbtl5.pas',
  Variable in 'System\Variable\Variable.pas',
  ReportPrint in 'Element\Report\ReportPrint.pas' {FrmReportPrint},
  ReportBrowse in 'Element\Report\ReportBrowse.pas' {FrmReportBrowse},
  ReportManager in 'Element\Report\ReportManager.pas',
  ReportInterface in 'Element\Report\ReportInterface.pas' {FrmReportInterface},
  daDOA in 'TP\extra\daDOA.pas',
  ReportSelect in 'Element\Report\ReportSelect.pas' {FrmReportSelect},
  ReportInterfaces in 'Element\Report\ReportInterfaces.pas',
  Report in 'Element\Report\Report.pas',
  ReportDataAccess in 'Element\Report\ReportDataAccess.pas',
  FolderInterfaces in 'Element\Report\FolderInterfaces.pas',
  Folder in 'Element\Report\Folder.pas',
  FolderDataAccess in 'Element\Report\FolderDataAccess.pas',
  TXtraDev in 'TP\extra\TxtraDev.pas',
  TXParse in 'TP\extra\TXPARSE.pas',
  TXTIFF in 'TP\extra\TXTIFF.pas',
  TXComp in 'TP\extra\TXCOMP.pas',
  ppMacro in 'Components\ppMacro.pas',
  ppMacro2 in 'Components\ppMacro2.pas',
  ppMacro3 in 'Components\ppMacro3.pas',
  MacroManager in 'System\Macro\MacroManager.pas',
  LayoutInterfaces in 'System\Layout\LayoutInterfaces.pas',
  Layout in 'System\Layout\Layout.pas',
  LayoutDataAccess in 'System\Layout\LayoutDataAccess.pas',
  MenuInterfaces in 'System\Menu\MenuInterfaces.pas',
  Menu in 'System\Menu\Menu.pas',
  MenuDataAccess in 'System\Menu\MenuDataAccess.pas',
  InterfaceManager in 'Interface\InterfaceManager.pas',
  EventMonitor in 'System\Debug\Monitoring\EventMonitor.pas',
  TransactionCreate in 'Element\Transaction\TransactionCreate.pas' {FrmTransactionCreate},
  dxDemoUtils in 'TP\dxGridStuff\dxDemoUtils.pas',
  dxEditUtils in 'TP\dxGridStuff\dxEditUtils.pas',
  dxGridMenus in 'TP\dxGridStuff\dxGridMenus.pas',
  ThreadSafeObjectQueue in 'System\Error\ThreadSafeObjectQueue.pas',
  StkTrace in 'System\Error\STKTRACE.PAS',
  Null in 'Components\Null.pas',
  LayoutManager in 'System\Layout\LayoutManager.pas',
  LayoutView in 'System\Layout\LayoutView.pas',
  Loader in 'Interface\Selection\Loader.pas',
  Opener in 'Interface\Selection\Opener.pas',
  StickerSelect in 'Element\Sticker\StickerSelect.pas' {FrmStickerSelect},
  StickerInterfaces in 'Element\Sticker\StickerInterfaces.pas',
  Sticker in 'Element\Sticker\Sticker.pas',
  StickerFolderInterfaces in 'Element\Sticker\StickerFolderInterfaces.pas',
  StickerFolder in 'Element\Sticker\StickerFolder.pas',
  StickerBrowse in 'Element\Sticker\StickerBrowse.pas' {FrmStickerBrowse},
  StickerPrint in 'Element\Sticker\StickerPrint.pas' {FrmStickerPrint},
  StickerManager in 'Element\Sticker\StickerManager.pas',
  StickerExplorer in 'Element\Sticker\StickerExplorer.pas' {FrmStickerExplorer},
  ItemReloaderDataAccess in 'Interface\Movement\ItemReloaderDataAccess.pas',
  AQDebug in 'System\AQTest\AQDebug.pas',
  Calculator in 'Interface\Miscellaneous\calculator.pas' {fmCalculator},
  Shares in 'System\Share\Shares.pas',
  Word_TLB in 'TP\Office\Word_TLB.pas',
  Excel_TLB in 'TP\Office\Excel_TLB.pas',
  Office_TLB in 'TP\Office\Office_TLB.pas',
  VBIDE_TLB in 'TP\Office\VBIDE_TLB.pas',
  StructureHelper in 'Element\Tree\StructureHelper.pas',
  SchemaColumns in 'System\Schema\SchemaColumns.pas',
  SchemaValues in 'System\Schema\SchemaValues.pas',
  SchemaTables in 'System\Schema\SchemaTables.pas',
  SchemaSizes in 'System\Schema\SchemaSizes.pas',
  Schema in 'System\Schema\Schema.pas',
  DummyCSIntf in 'System\Debug\CodeSite\DummyCSIntf.pas',
  ReportBuilderDataAccess in 'Element\Report\ReportBuilderDataAccess.pas',
  RBTable in 'Element\Report\RBTable.pas',
  RBField in 'Element\Report\RBField.pas',
  RBJoin in 'Element\Report\RBJoin.pas',
  DBHelper in 'System\Database\DBHelper.pas',
  SelectionManagerDataAccess in 'Interface\Selection\SelectionManagerDataAccess.pas',
  StateMachineInterfaces in 'Pattern\StateMachineInterfaces.pas',
  StateMachine in 'Pattern\StateMachine.pas',
  StEvents in 'System\Event\StEvents.pas',
  llUtilities in 'System\Utilities\llUtilities.pas',
  StExceptions in 'System\Error\StExceptions.pas',
  StMacros in 'System\Macro\StMacros.pas',
  LayoutBrowseTemporary in 'System\Layout\LayoutBrowseTemporary.pas' {FrmLayoutBrowseTemporary},
  PersistenceInterfaces in 'System\Persistence\PersistenceInterfaces.pas',
  DatabaseInterfaces in 'System\Database\DatabaseInterfaces.pas',
  HeirachyInterfaces in 'System\Heirachy\HeirachyInterfaces.pas',
  ThingInterfaces in 'System\Thing\ThingInterfaces.pas',
  CacheInterfaces in 'System\Cache\CacheInterfaces.pas',
  Cache in 'System\Cache\Cache.pas',
  ComObjEx in 'System\Extension\ComObjEx.pas',
  Thing in 'System\Thing\Thing.pas',
  WorkstationManager in 'System\Configuration\Workstation\WorkstationManager.pas',
  OperatorManager in 'System\Operator\OperatorManager.pas',
  OperatorManagerInterfaces in 'System\Operator\OperatorManagerInterfaces.pas',
  SecurityManagerInterfaces in 'System\Security\SecurityManagerInterfaces.pas',
  LoginManager in 'System\Login\LoginManager.pas',
  LoginManagerInterfaces in 'System\Login\LoginManagerInterfaces.pas',
  COMHelper in 'System\Extension\COMHelper.pas',
  HeirachyHelper in 'System\Heirachy\HeirachyHelper.pas',
  InterfaceStack in 'UTILS\InterfaceStack.pas',
  SelectionManagerInterfaces in 'Interface\Selection\SelectionManagerInterfaces.pas',
  MatchInterfaces in 'System\Match\MatchInterfaces.pas',
  ReferenceInterfaces in 'System\Reference\ReferenceInterfaces.pas',
  NumberUtilities in 'UTILS\NumberUtilities.pas',
  MiscellaneousInterfaces in 'System\Miscellaneous\MiscellaneousInterfaces.pas',
  Database in 'System\Database\Database.pas',
  ConfigurationInterfaces in 'System\Configuration\ConfigurationInterfaces.pas',
  doaDatabaseInterfaces in 'System\Database\doa\doaDatabaseInterfaces.pas',
  WaitInterfaces in 'System\IdleOrBusy\WaitInterfaces.pas',
  FormInterfaces in 'System\Extension\FormInterfaces.pas',
  SplashInterfaces in 'Main\Splash\SplashInterfaces.pas',
  RAMInterfaces in 'System\Configuration\RAMInterfaces.pas',
  SaverInterfaces in 'System\IdleOrBusy\SaverInterfaces.pas',
  ApplicationInterfaces in 'System\Configuration\ApplicationInterfaces.pas',
  OSInterfaces in 'System\Configuration\OSInterfaces.pas',
  HDInterfaces in 'System\Configuration\HDInterfaces.pas',
  NetworkInterfaces in 'System\Configuration\NetworkInterfaces.pas',
  CPUInterfaces in 'System\Configuration\CPUInterfaces.pas',
  InterfaceManagerInterfaces in 'Interface\InterfaceManagerInterfaces.pas',
  ClockInterfaces in 'System\Clock\ClockInterfaces.pas',
  TickerInterfaces in 'System\Ticker\TickerInterfaces.pas',
  OpenerInterfaces in 'Interface\Selection\OpenerInterfaces.pas',
  StatusBarManagerInterfaces in 'System\Status\StatusBarManagerInterfaces.pas',
  ClipboardInterfaces in 'System\Clipboard\ClipboardInterfaces.pas',
  SplashHelper in 'Main\Splash\SplashHelper.pas',
  SchemaUtilities in 'System\Schema\SchemaUtilities.pas',
  SchemaInterfaces in 'System\Schema\SchemaInterfaces.pas',
  SchemaDataAccess in 'System\Schema\SchemaDataAccess.pas',
  NexusHelper in 'Main\Nexus\NexusHelper.pas',
  ClassTypes in 'System\Heirachy\ClassTypes.pas',
  WorkstationManagerInterfaces in 'System\Configuration\Workstation\WorkstationManagerInterfaces.pas',
  ThingTypes in 'System\Thing\ThingTypes.pas',
  ViewManagerInterfaces in 'Interface\View\ViewManagerInterfaces.pas',
  StickerManagerInterfaces in 'Element\Sticker\StickerManagerInterfaces.pas',
  ReportManagerInterfaces in 'Element\Report\ReportManagerInterfaces.pas',
  MacroManagerInterfaces in 'System\Macro\MacroManagerInterfaces.pas',
  CacheHelper in 'System\Cache\CacheHelper.pas',
  ContactInterfaces in 'System\Contact\ContactInterfaces.pas',
  MultiplierInterfaces in 'System\Dimension\MultiplierInterfaces.pas',
  ComplexInterfaces in 'System\Dimension\ComplexInterfaces.pas',
  DimensionInterfaces in 'System\Dimension\DimensionInterfaces.pas',
  MeasureInterfaces in 'System\Dimension\MeasureInterfaces.pas',
  MeasureIsInterfaces in 'System\Dimension\MeasureIsInterfaces.pas',
  AttributeIsInterfaces in 'Element\Attribute\AttributeIsInterfaces.pas',
  AttributeInterfaces in 'Element\Attribute\AttributeInterfaces.pas',
  Attribute in 'Element\Attribute\Attribute.pas',
  AttributeIs in 'Element\Attribute\AttributeIs.pas',
  AttributeDataAccess in 'Element\Attribute\AttributeDataAccess.pas',
  AttributeIsDataAccess in 'Element\Attribute\AttributeIsDataAccess.pas',
  Contact in 'System\Contact\Contact.pas',
  ContactDataAccess in 'System\Contact\ContactDataAccess.pas',
  Multiplier in 'System\Dimension\Multiplier.pas',
  MultiplierDataAccess in 'System\Dimension\MultiplierDataAccess.pas',
  Complex in 'System\Dimension\Complex.pas',
  ComplexDataAccess in 'System\Dimension\ComplexDataAccess.pas',
  Dimension in 'System\Dimension\Dimension.pas',
  DimensionDataAccess in 'System\Dimension\DimensionDataAccess.pas',
  Measure in 'System\Dimension\Measure.pas',
  MeasureDataAccess in 'System\Dimension\MeasureDataAccess.pas',
  MeasureIs in 'System\Dimension\MeasureIs.pas',
  MeasureIsDataAccess in 'System\Dimension\MeasureIsDataAccess.pas',
  DimensionManager in 'System\Conversion\DimensionManager.pas',
  DimensionManagerInterfaces in 'System\Conversion\DimensionManagerInterfaces.pas',
  ConversionManagerInterfaces in 'System\Conversion\ConversionManagerInterfaces.pas',
  ConversionManager in 'System\Conversion\ConversionManager.pas',
  ValueInterfaces in 'System\Conversion\ValueInterfaces.pas',
  ValueManagerInterfaces in 'System\Conversion\ValueManagerInterfaces.pas',
  ValueManager in 'System\Conversion\ValueManager.pas',
  Value in 'System\Conversion\Value.pas',
  DimensionBrowse in 'System\Dimension\DimensionBrowse.pas' {FrmDimensionBrowse},
  CollectionIsInterfaces in 'Element\Collection\CollectionIsInterfaces.pas',
  CollectionIsDataAccess in 'Element\Collection\CollectionIsDataAccess.pas',
  CollectionIs in 'Element\Collection\CollectionIs.pas',
  ItemIs in 'Element\Item\ItemIs.pas',
  ItemIsInterfaces in 'Element\Item\ItemIsInterfaces.pas',
  ItemIsDataAccess in 'Element\Item\ItemIsDataAccess.pas',
  ComplexBrowse in 'System\Dimension\ComplexBrowse.pas' {FrmComplexBrowse},
  MeasureBrowse in 'System\Dimension\MeasureBrowse.pas' {FrmMeasureBrowse},
  MeasureIsBrowse in 'System\Dimension\MeasureIsBrowse.pas' {FrmMeasureIsBrowse},
  TransactionIsInterfaces in 'Element\Transaction\TransactionIsInterfaces.pas',
  CollectionManager in 'Element\Collection\CollectionManager.pas',
  CollectionManagerInterfaces in 'Element\Collection\CollectionManagerInterfaces.pas',
  StructureManagerInterfaces in 'Element\Tree\StructureManagerInterfaces.pas',
  StructureManager in 'Element\Tree\StructureManager.pas',
  ItemManagerInterfaces in 'Element\Item\ItemManagerInterfaces.pas',
  ItemManager in 'Element\Item\ItemManager.pas',
  Store in 'System\Thing\Store.pas',
  StoreInterfaces in 'System\Thing\StoreInterfaces.pas',
  MovementManager in 'Interface\Movement\MovementManager.pas',
  MovementManagerInterfaces in 'Interface\Movement\MovementManagerInterfaces.pas',
  Manual in 'Interface\Movement\Manual.pas',
  ManualInterfaces in 'Interface\Movement\ManualInterfaces.pas',
  MovementStates in 'Interface\Movement\MovementStates.pas',
  ManualRegister in 'Interface\Action\Register\ManualRegister.pas' {FrmManualRegister},
  TransactionManager in 'Element\Transaction\TransactionManager.pas',
  TransactionManagerInterfaces in 'Element\Transaction\TransactionManagerInterfaces.pas',
  TransactionIs in 'Element\Transaction\Transactionis.pas',
  TransactionIsDataAccess in 'Element\Transaction\transactionisDataAccess.pas',
  WizardTemplate in 'Interface\Wizard\WizardTemplate.pas' {frmWizardTemplate},
  WizardInterfaces in 'Interface\Wizard\WizardInterfaces.pas',
  WizardManagerInterfaces in 'Interface\Wizard\WizardManagerInterfaces.pas',
  RegisterManagerInterfaces in 'Interface\Action\Register\RegisterManagerInterfaces.pas',
  RegisterManager in 'Interface\Action\Register\RegisterManager.pas',
  WizardManager in 'Interface\Wizard\WizardManager.pas',
  Wizard in 'Interface\Wizard\Wizard.pas',
  WizardToForm in 'Interface\Wizard\WizardToForm.pas',
  WizardToFormInterfaces in 'Interface\Wizard\WizardToFormInterfaces.pas',
  TransactionFrame in 'Element\Transaction\TransactionFrame.pas' {fraTransaction: TFrame},
  ItemFrame in 'Element\Item\ItemFrame.pas' {fraItem: TFrame},
  MovementTo in 'Interface\Movement\MovementTo.pas',
  MovementInterfaces in 'Interface\Movement\MovementInterfaces.pas',
  VersionInterfaces in 'System\Version\VersionInterfaces.pas',
  llHeirachy in 'System\llHeirachy.pas',
  Frame in 'Interface\Frame\Frame.pas' {FrameTemplate: TFrame},
  FrameInterfaces in 'Interface\Frame\FrameInterfaces.pas',
  TransactionSection in 'Element\Transaction\TransactionSection.pas',
  Movement in 'Interface\Movement\Movement.pas',
  ContactManager in 'System\Contact\ContactManager.pas',
  ContactManagerInterfaces in 'System\Contact\ContactManagerInterfaces.pas',
  ContextInterfaces in 'System\Context\ContextInterfaces.pas',
  OwnerInterfaces in 'System\Owner\OwnerInterfaces.pas',
  Owner in 'System\Owner\Owner.pas',
  Transaction2 in 'Element\Transaction\Transaction2.pas',
  Debugger in 'System\Debug\Debugger.pas',
  DebuggerTemplate in 'System\Debug\DebuggerTemplate.pas' {FrmDebugger},
  DebuggerInterfaces in 'System\Debug\DebuggerInterfaces.pas',
  CacheDebugger in 'System\Cache\CacheDebugger.pas' {fraDebugCacheFrame: TFrame},
  DebuggerHelper in 'System\Debug\DebuggerHelper.pas',
  Contact2 in 'System\Contact\Contact2.pas',
  EncryptionInterfaces in 'System\Encryption\EncryptionInterfaces.pas',
  MovementDataAccess in 'Interface\Movement\MovementDataAccess.pas',
  FromDataAccess in 'Interface\Movement\FromDataAccess.pas',
  IDInterfaces in 'System\Heirachy\IDInterfaces.pas',
  ID in 'System\Heirachy\ID.pas',
  IntoDataAccess in 'Interface\Movement\IntoDataAccess.pas',
  NullInterfaces in 'Components\NullInterfaces.pas',
  GridManagerInterfaces in 'Interface\Grid\GridManagerInterfaces.pas',
  SchemaManagerInterfaces in 'System\Schema\SchemaManagerInterfaces.pas',
  SchemaManager in 'System\Schema\SchemaManager.pas',
  SchemaTableInterfaces in 'System\Schema\SchemaTableInterfaces.pas',
  SchemaColumnDataAccess in 'System\Schema\SchemaColumnDataAccess.pas',
  SchemaTableDataAccess in 'System\Schema\SchemaTableDataAccess.pas',
  SchemaColumn in 'System\Schema\SchemaColumn.pas',
  SchemaColumnInterfaces in 'System\Schema\SchemaColumnInterfaces.pas',
  SchemaTable in 'System\Schema\SchemaTable.pas',
  AttributeManager in 'Element\Attribute\AttributeManager.pas',
  AttributeManagerInterfaces in 'Element\Attribute\AttributeManagerInterfaces.pas',
  MeasureManagerInterfaces in 'System\Dimension\MeasureManagerInterfaces.pas',
  MeasureManager in 'System\Dimension\MeasureManager.pas',
  WinCRTDebugger in 'System\Debug\WinCRTDebugger.pas' {fraDebugWinCRTFrame: TFrame},
  WinCRT in 'System\Debug\WinCRT.pas',
  StInterfaceList in 'System\Extension\StInterfaceList.pas',
  TraceDebugger in 'System\Debug\TraceDebugger.pas',
  ManagerInterfaces in 'System\Manager\ManagerInterfaces.pas',
  Manager in 'System\Manager\Manager.pas',
  LinkerInterfaces in 'System\Linker\LinkerInterfaces.pas',
  Linker in 'System\Linker\Linker.pas',
  LinkerManagerInterfaces in 'System\Linker\LinkerManagerInterfaces.pas',
  StComObjEx in 'System\Extension\StComObjEx.pas',
  LinkerManager in 'System\Linker\LinkerManager.pas',
  Logic in 'System\Logic\Logic.pas',
  Context in 'System\Context\Context.pas',
  DataInterfaces in 'System\Data\DataInterfaces.pas',
  AddManagerInterfaces in 'Interface\Action\Add\AddManagerInterfaces.pas',
  AddManager in 'Interface\Action\Add\AddManager.pas',
  InterfaceStore in 'Interface\InterfaceStore.pas',
  InterfaceStoreInterfaces in 'Interface\InterfaceStoreInterfaces.pas',
  ThingHelper in 'System\Thing\ThingHelper.pas',
  FilterInterfaces in 'System\Filter\FilterInterfaces.pas',
  Filter in 'System\Filter\Filter.pas',
  OperatorHelper in 'System\Operator\OperatorHelper.pas',
  MacroHelper in 'System\Macro\MacroHelper.pas',
  Item2 in 'Element\Item\Item2.pas',
  ListInterfaces in 'System\List\ListInterfaces.pas',
  List in 'System\List\List.pas',
  ListHelper in 'System\List\ListHelper.pas',
  BookHelper in 'Interface\book\BookHelper.pas',
  ItemIsFrame in 'Element\Item\ItemIsFrame.pas' {FraItemIs: TFrame},
  BrowseInterfaces in 'Interface\Browse\BrowseInterfaces.pas',
  BrowseTemplate in 'Interface\Browse\BrowseTemplate.pas' {FrmBrowseTemplate},
  Browse in 'Interface\Browse\Browse.pas',
  BrowseManager in 'Interface\Browse\BrowseManager.pas',
  BrowseManagerInterfaces in 'Interface\Browse\BrowseManagerInterfaces.pas',
  ItemIsBrowse in 'Element\Item\ItemIsBrowse.pas',
  BrowseHelper in 'Interface\Browse\BrowseHelper.pas',
  Template in 'Interface\Frame\Template.pas' {FrameTemplate1: TFrame},
  TransactionIsBrowse in 'Element\Transaction\TransactionIsBrowse.pas',
  TransactionIsSection in 'Element\Transaction\TransactionIsSection.pas',
  TransactionIsFrame in 'Element\Transaction\TransactionIsFrame.pas' {FraTransactionIs: TFrame},
  CollectionIsFrame in 'Element\Collection\CollectionIsFrame.pas' {FraCollectionIs: TFrame},
  CollectionIsSection in 'Element\Collection\CollectionIsSection.pas',
  CollectionIsBrowse in 'Element\Collection\CollectionIsBrowse.pas',
  cLLListBox in 'Components\cLLListBox.pas',
  AttributeIsBrowse in 'Element\Attribute\AttributeIsBrowse.pas',
  AttributeIsSection in 'Element\Attribute\AttributeIsSection.pas',
  AttributeIsFrame in 'Element\Attribute\AttributeIsFrame.pas' {FraAttributeIs: TFrame},
  MultiplierSection in 'System\Dimension\MultiplierSection.pas',
  MultiplierBrowse in 'System\Dimension\MultiplierBrowse.pas',
  MultiplierFrame in 'System\Dimension\MultiplierFrame.pas' {FraMultiplier: TFrame},
  SchemaHelper in 'System\Schema\SchemaHelper.pas',
  WinCRTInterfaces in 'System\Debug\WinCRTInterfaces.pas',
  llDebugger in 'System\Debug\llDebugger.pas',
  llWinCRT in 'System\Debug\llWinCRT.pas',
  MeasureIsFrame in 'System\Dimension\MeasureIsFrame.pas' {FraMeasureIs: TFrame},
  MeasureIsSection in 'System\Dimension\MeasureIsSection.pas',
  ComplexSection in 'System\Dimension\ComplexSection.pas',
  ComplexFrame in 'System\Dimension\complexframe.pas' {FraComplex: TFrame},
  MeasureSection in 'System\Dimension\MeasureSection.pas',
  DimensionFrame in 'System\Dimension\DimensionFrame.pas' {FraDimension: TFrame},
  DimensionSection in 'System\Dimension\DimensionSection.pas',
  MeasureFrame in 'System\Dimension\measureframe.pas' {FraMeasure: TFrame},
  FormatSection in 'System\Dimension\FormatSection.pas',
  FormatDataAccess in 'System\Dimension\FormatDataAccess.pas',
  Format in 'System\Dimension\Format.pas',
  FormatBrowse in 'System\Dimension\FormatBrowse.pas',
  FormatFrame in 'System\Dimension\FormatFrame.pas' {FraFormat: TFrame},
  FormatInterfaces in 'System\Dimension\FormatInterfaces.pas',
  DataAccess in 'System\Database\DataAccess.pas',
  DAUtilities in 'System\Database\DAUtilities.pas',
  WizardStartFrame in 'Interface\Wizard\WizardStartFrame.pas' {fraWizardStart: TFrame},
  WizardFinishFrame in 'Interface\Wizard\WizardFinishFrame.pas' {fraWizardFinish: TFrame},
  WizardFinishSection in 'Interface\Wizard\WizardFinishSection.pas',
  WizardStartSection in 'Interface\Wizard\WizardStartSection.pas',
  AttributeSection in 'Element\Attribute\AttributeSection.pas',
  AttributeFloatFrame in 'Element\Attribute\AttributeFloatFrame.pas' {FraAttributeFloat: TFrame},
  SchemaUserSection in 'Interface\Schema\SchemaUserSection.pas',
  SchemaUserFrame in 'Interface\Schema\SchemaUserFrame.pas' {FraSchemaUser: TFrame},
  SchemaStore in 'Interface\Schema\SchemaStore.pas',
  BasicInterfaces in 'System\Thing\BasicInterfaces.pas',
  SchemaViewSection in 'Interface\Schema\SchemaViewSection.pas',
  SchemaColumnFrame in 'Interface\Schema\SchemaColumnFrame.pas' {FraSchemaColumn: TFrame},
  SchemaColumnSection in 'Interface\Schema\SchemaColumnSection.pas',
  SchemaTableFrame in 'Interface\Schema\SchemaTableFrame.pas' {FraSchemaTable: TFrame},
  SchemaTableSection in 'Interface\Schema\SchemaTableSection.pas',
  SchemaViewFrame in 'Interface\Schema\SchemaViewFrame.pas' {FraSchemaView: TFrame},
  SchemaStoreInterfaces in 'Interface\Schema\SchemaStoreInterfaces.pas',
  SchemaSequenceFrame in 'Interface\Schema\SchemaSequenceFrame.pas' {FraSchemaSequence: TFrame},
  SchemaSequenceSection in 'Interface\Schema\SchemaSequenceSection.pas',
  SchemaConstraintFrame in 'Interface\Schema\SchemaConstraintFrame.pas' {FraSchemaConstraint: TFrame},
  SchemaConstraintSection in 'Interface\Schema\SchemaConstraintSection.pas',
  SchemaIndexFrame in 'Interface\Schema\SchemaIndexFrame.pas' {FraSchemaIndex: TFrame},
  SchemaIndexSection in 'Interface\Schema\SchemaIndexSection.pas',
  SchemaKeyFrame in 'Interface\Schema\SchemaKeyFrame.pas' {FraSchemaKey: TFrame},
  SchemaKeySection in 'Interface\Schema\SchemaKeySection.pas',
  SchemaReferenceFrame in 'Interface\Schema\SchemaReferenceFrame.pas' {FraSchemaReference: TFrame},
  SchemaReferenceSection in 'Interface\Schema\SchemaReferenceSection.pas',
  GridManagerDataAccess in 'Interface\Grid\GridManagerDataAccess.pas',
  DAInterfaces in 'System\Database\DAInterfaces.pas',
  ViewManager in 'Interface\View\ViewManager.pas',
  SQL in 'System\Database\SQL.pas',
  SQLInterfaces in 'System\Database\SQLInterfaces.pas',
  ListUtilities in 'System\List\ListUtilities.pas',
  NotifyInterfaces in 'System\Notify\NotifyInterfaces.pas',
  StacyInterfaces in 'Main\StacyInterfaces.pas',
  StacyImplementations in 'Main\StacyImplementations.pas',
  Apply in 'Element\Attribute\Apply.pas',
  ApplyInterfaces in 'Element\Attribute\ApplyInterfaces.pas',
  ApplyDataAccess in 'Element\Attribute\ApplyDataAccess.pas',
  Lob in 'System\LOB\Lob.pas',
  ComplexTypes in 'System\Dimension\ComplexTypes.pas',
  DimensionHelper in 'System\Dimension\DimensionHelper.pas',
  TransactionIsTypes in 'Element\Transaction\TransactionIsTypes.pas',
  AnalyseSection in 'Element\analyse\AnalyseSection.PAS',
  Analyse in 'Element\analyse\Analyse.PAS',
  AnalyseDataAccess in 'Element\analyse\AnalyseDataAccess.PAS',
  AnalyseFrame in 'Element\analyse\AnalyseFrame.PAS',
  AnalyseInterfaces in 'Element\analyse\AnalyseInterfaces.PAS',
  AnalyseIs in 'Element\analyse\AnalyseIs.PAS',
  AnalyseIsDataAccess in 'Element\analyse\AnalyseIsDataAccess.PAS',
  AnalyseIsFrame in 'Element\analyse\AnalyseIsFrame.PAS',
  AnalyseIsInterfaces in 'Element\analyse\AnalyseIsInterfaces.PAS',
  AnalyseIsSection in 'Element\analyse\AnalyseIsSection.PAS',
  AssociateSection in 'Element\Associate\AssociateSection.PAS',
  ApplySection in 'Element\Associate\ApplySection.PAS',
  Associate in 'Element\Associate\Associate.PAS',
  Associated in 'Element\Associate\Associated.PAS',
  AssociateDataAccess in 'Element\Associate\AssociateDataAccess.PAS',
  AssociatedDataAccess in 'Element\Associate\AssociatedDataAccess.PAS',
  AssociatedFrame in 'Element\Associate\AssociatedFrame.PAS' {FraAssociated: TFrame},
  AssociatedInterfaces in 'Element\Associate\AssociatedInterfaces.PAS',
  AssociatedSection in 'Element\Associate\AssociatedSection.PAS',
  AssociateFrame in 'Element\Associate\AssociateFrame.PAS' {FraAssociate: TFrame},
  AssociateInterfaces in 'Element\Associate\AssociateInterfaces.PAS',
  AssociateIs in 'Element\Associate\AssociateIs.PAS',
  AssociateIsDataAccess in 'Element\Associate\AssociateIsDataAccess.PAS',
  AssociateIsFrame in 'Element\Associate\AssociateIsFrame.PAS' {FraAssociateIs: TFrame},
  AssociateIsInterfaces in 'Element\Associate\AssociateIsInterfaces.PAS',
  AssociateIsSection in 'Element\Associate\AssociateIsSection.PAS',
  PageSection in 'Element\Attribute\PageSection.PAS',
  Include in 'Element\Attribute\Include.PAS',
  IncludeDataAccess in 'Element\Attribute\IncludeDataAccess.PAS',
  IncludeFrame in 'Element\Attribute\IncludeFrame.PAS' {FraInclude: TFrame},
  IncludeInterfaces in 'Element\Attribute\IncludeInterfaces.PAS',
  IncludeSection in 'Element\Attribute\IncludeSection.PAS',
  Page in 'Element\Attribute\Page.PAS',
  PageDataAccess in 'Element\Attribute\PageDataAccess.PAS',
  PageFrame in 'Element\Attribute\PageFrame.PAS',
  PageInterfaces in 'Element\Attribute\PageInterfaces.PAS',
  CollectionSnapshotSection in 'Element\Collection\CollectionSnapshotSection.PAS',
  CollectionFrame in 'Element\Collection\CollectionFrame.PAS' {FraCollection: TFrame},
  CollectionHistory in 'Element\Collection\CollectionHistory.PAS',
  CollectionHistoryDataAccess in 'Element\Collection\CollectionHistoryDataAccess.PAS',
  CollectionHistoryFrame in 'Element\Collection\CollectionHistoryFrame.PAS' {FraCollectionHistory: TFrame},
  CollectionHistoryInterfaces in 'Element\Collection\CollectionHistoryInterfaces.PAS',
  CollectionHistorySection in 'Element\Collection\CollectionHistorySection.PAS',
  CollectionSection in 'Element\Collection\CollectionSection.PAS',
  CollectionSnapshot in 'Element\Collection\CollectionSnapshot.PAS',
  CollectionSnapshotDataAccess in 'Element\Collection\CollectionSnapshotDataAccess.PAS',
  CollectionSnapshotFrame in 'Element\Collection\CollectionSnapshotFrame.PAS' {FraCollectionSnapshot: TFrame},
  CollectionSnapshotInterfaces in 'Element\Collection\CollectionSnapshotInterfaces.PAS',
  CombinationSection in 'Element\Combination\CombinationSection.PAS',
  Combination in 'Element\Combination\Combination.PAS',
  Combinationattribute in 'Element\Combination\Combinationattribute.PAS',
  CombinationattributeDataAccess in 'Element\Combination\CombinationattributeDataAccess.PAS',
  CombinationattributeFrame in 'Element\Combination\CombinationattributeFrame.PAS' {FraCombinationattribute: TFrame},
  CombinationattributeInterfaces in 'Element\Combination\CombinationattributeInterfaces.PAS',
  CombinationattributeSection in 'Element\Combination\CombinationattributeSection.PAS',
  CombinationDataAccess in 'Element\Combination\CombinationDataAccess.PAS',
  CombinationFrame in 'Element\Combination\CombinationFrame.PAS' {FraCombination: TFrame},
  CombinationInterfaces in 'Element\Combination\CombinationInterfaces.PAS',
  CompoundSection in 'Element\Compound\CompoundSection.PAS',
  Compound in 'Element\Compound\Compound.PAS',
  CompoundDataAccess in 'Element\Compound\CompoundDataAccess.PAS',
  CompoundFrame in 'Element\Compound\CompoundFrame.PAS' {FraCompound: TFrame},
  CompoundInterfaces in 'Element\Compound\CompoundInterfaces.PAS',
  CompoundIs in 'Element\Compound\CompoundIs.PAS',
  CompoundIsDataAccess in 'Element\Compound\CompoundIsDataAccess.PAS',
  CompoundIsFrame in 'Element\Compound\CompoundIsFrame.PAS' {FraCompoundIs: TFrame},
  CompoundIsInterfaces in 'Element\Compound\CompoundIsInterfaces.PAS',
  CompoundIsSection in 'Element\Compound\CompoundIsSection.PAS',
  ContainmentSection in 'Element\Containment\ContainmentSection.PAS',
  ContainmentDataAccess in 'Element\Containment\ContainmentDataAccess.PAS',
  ContainmentFrame in 'Element\Containment\ContainmentFrame.PAS' {FraContainment: TFrame},
  ElementSection in 'Element\Element\ElementSection.PAS',
  Element in 'Element\Element\Element.PAS',
  ElementDataAccess in 'Element\Element\ElementDataAccess.PAS',
  ElementFrame in 'Element\Element\ElementFrame.PAS' {FraElement: TFrame},
  ElementInterfaces in 'Element\Element\ElementInterfaces.PAS',
  IsotopeSection in 'Element\Isotope\IsotopeSection.PAS',
  Isotope in 'Element\Isotope\Isotope.PAS',
  IsotopeDataAccess in 'Element\Isotope\IsotopeDataAccess.PAS',
  IsotopeFrame in 'Element\Isotope\IsotopeFrame.PAS' {FraIsotope: TFrame},
  IsotopeInterfaces in 'Element\Isotope\IsotopeInterfaces.PAS',
  ApplyFrame in 'Element\Attribute\ApplyFrame.pas' {FraApply: TFrame},
  FolderFrame in 'Element\Report\FolderFrame.PAS' {FraFolder: TFrame},
  FolderSection in 'Element\Report\FolderSection.PAS',
  ReportFrame in 'Element\Report\ReportFrame.PAS' {FraReport: TFrame},
  ReportSection in 'Element\Report\ReportSection.PAS',
  StatusSection in 'Element\Status\StatusSection.PAS',
  Status in 'Element\Status\Status.PAS',
  StatusDataAccess in 'Element\Status\StatusDataAccess.PAS',
  StatusFrame in 'Element\Status\StatusFrame.PAS',
  StatusInterfaces in 'Element\Status\StatusInterfaces.PAS',
  StatusIs in 'Element\Status\StatusIs.PAS',
  StatusIsDataAccess in 'Element\Status\StatusIsDataAccess.PAS',
  StatusIsFrame in 'Element\Status\StatusIsFrame.PAS',
  StatusIsInterfaces in 'Element\Status\StatusIsInterfaces.PAS',
  StatusIsSection in 'Element\Status\StatusIsSection.PAS',
  StudySection in 'Element\study\StudySection.PAS',
  Study in 'Element\study\Study.PAS',
  StudyDataAccess in 'Element\study\StudyDataAccess.PAS',
  StudyFrame in 'Element\study\StudyFrame.PAS' {FraStudy: TFrame},
  StudyInterfaces in 'Element\study\StudyInterfaces.PAS',
  StudyIs in 'Element\study\StudyIs.PAS',
  StudyIsDataAccess in 'Element\study\StudyIsDataAccess.PAS',
  StudyIsFrame in 'Element\study\StudyIsFrame.PAS' {FraStudyIs: TFrame},
  StudyIsInterfaces in 'Element\study\StudyIsInterfaces.PAS',
  StudyIsSection in 'Element\study\StudyIsSection.PAS',
  ItemSelection in 'Element\Tracking\itemselection.pas' {FrmItemSelection},
  ContentFrame in 'Element\Tracking\ContentFrame.PAS' {FraContent: TFrame},
  ContentSection in 'Element\Tracking\ContentSection.PAS',
  StructureFrame in 'Element\Tree\StructureFrame.PAS' {FraStructure: TFrame},
  StructureSection in 'Element\Tree\StructureSection.PAS',
  AuditEvent in 'System\Audit\AuditEvent.PAS',
  AuditEventDataAccess in 'System\Audit\AuditEventDataAccess.PAS',
  AuditEventFrame in 'System\Audit\AuditEventFrame.PAS' {FraAuditEvent: TFrame},
  AuditEventInterfaces in 'System\Audit\AuditEventInterfaces.PAS',
  AuditEventSection in 'System\Audit\AuditEventSection.PAS',
  AuditPreview in 'System\Audit\AuditPreview.pas' {FrmAuditPreview},
  Auditreason in 'System\Audit\Auditreason.PAS',
  AuditreasonDataAccess in 'System\Audit\AuditreasonDataAccess.PAS',
  AuditreasonFrame in 'System\Audit\AuditreasonFrame.PAS' {FraAuditreason: TFrame},
  AuditreasonInterfaces in 'System\Audit\AuditreasonInterfaces.PAS',
  AuditreasonSection in 'System\Audit\AuditreasonSection.PAS',
  WorkstationSection in 'System\Configuration\Workstation\WorkstationSection.PAS',
  WorkstationFrame in 'System\Configuration\Workstation\WorkstationFrame.PAS' {FraWorkstation: TFrame},
  ContactFrame in 'System\Contact\ContactFrame.PAS' {FraContact: TFrame},
  ContactSection in 'System\Contact\ContactSection.PAS',
  Debug in 'System\Error\debug.pas',
  Error in 'System\Error\Error.PAS',
  ErrorDataAccess in 'System\Error\ErrorDataAccess.PAS',
  ErrorFrame in 'System\Error\ErrorFrame.PAS' {FraError: TFrame},
  ErrorInterfaces in 'System\Error\ErrorInterfaces.PAS',
  ErrorSection in 'System\Error\ErrorSection.PAS',
  IconSection in 'System\Icon\IconSection.PAS',
  Icon in 'System\Icon\Icon.PAS',
  IconDataAccess in 'System\Icon\IconDataAccess.PAS',
  IconFrame in 'System\Icon\IconFrame.PAS' {FraIcon: TFrame},
  IconInterfaces in 'System\Icon\IconInterfaces.PAS',
  LayoutFrame in 'System\Layout\LayoutFrame.PAS' {FraLayout: TFrame},
  LayoutSection in 'System\Layout\LayoutSection.PAS',
  LicenseFrame in 'System\License\LicenseFrame.PAS' {FraLicense: TFrame},
  Licenseoption in 'System\License\Licenseoption.PAS',
  LicenseoptionDataAccess in 'System\License\LicenseoptionDataAccess.PAS',
  LicenseoptionFrame in 'System\License\LicenseoptionFrame.PAS' {FraLicenseoption: TFrame},
  LicenseoptionInterfaces in 'System\License\LicenseoptionInterfaces.PAS',
  LicenseoptionSection in 'System\License\LicenseoptionSection.PAS',
  LicenseSection in 'System\License\LicenseSection.PAS',
  LimitSection in 'System\Limit\LimitSection.PAS',
  Limit in 'System\Limit\Limit.PAS',
  Limitapply in 'System\Limit\Limitapply.PAS',
  LimitapplyDataAccess in 'System\Limit\LimitapplyDataAccess.PAS',
  LimitapplyFrame in 'System\Limit\LimitapplyFrame.PAS' {FraLimitapply: TFrame},
  LimitapplyInterfaces in 'System\Limit\LimitapplyInterfaces.PAS',
  LimitapplySection in 'System\Limit\LimitapplySection.PAS',
  LimitDataAccess in 'System\Limit\LimitDataAccess.PAS',
  LimitEvent in 'System\Limit\LimitEvent.PAS',
  LimitEventDataAccess in 'System\Limit\LimitEventDataAccess.PAS',
  LimitEventFrame in 'System\Limit\LimitEventFrame.PAS' {FraLimitEvent: TFrame},
  LimitEventInterfaces in 'System\Limit\LimitEventInterfaces.PAS',
  LimitEventSection in 'System\Limit\LimitEventSection.PAS',
  LimitFrame in 'System\Limit\LimitFrame.PAS' {FraLimit: TFrame},
  LimitInterfaces in 'System\Limit\LimitInterfaces.PAS',
  LockedSection in 'System\Locked\LockedSection.PAS',
  Locked in 'System\Locked\Locked.PAS',
  LockedDataAccess in 'System\Locked\LockedDataAccess.PAS',
  LockedFrame in 'System\Locked\LockedFrame.PAS' {FraLocked: TFrame},
  LockedInterfaces in 'System\Locked\LockedInterfaces.PAS',
  PasswordsecuritySection in 'System\Password\PasswordsecuritySection.PAS',
  LoginHistoryFrame in 'System\Login\LoginHistoryFrame.PAS' {FraLoginHistory: TFrame},
  LoginHistoryInterfaces in 'System\Login\LoginHistoryInterfaces.PAS',
  LoginHistorySection in 'System\Login\LoginHistorySection.PAS',
  LoginNamesecurity in 'System\Login\Loginnamesecurity.PAS',
  LoginNamesecurityDataAccess in 'System\Login\LoginNamesecurityDataAccess.PAS',
  LoginNamesecurityFrame in 'System\Login\LoginNamesecurityFrame.PAS' {FraLoginNamesecurity: TFrame},
  LoginNamesecurityInterfaces in 'System\Login\LoginNamesecurityInterfaces.PAS',
  LoginNamesecuritySection in 'System\Login\LoginNamesecuritySection.PAS',
  Loginrecording in 'System\Login\Loginrecording.PAS',
  LoginrecordingDataAccess in 'System\Login\LoginrecordingDataAccess.PAS',
  LoginrecordingFrame in 'System\Login\LoginrecordingFrame.PAS' {FraLoginrecording: TFrame},
  LoginrecordingInterfaces in 'System\Login\LoginrecordingInterfaces.PAS',
  LoginrecordingSection in 'System\Login\LoginrecordingSection.PAS',
  Loginsecurity in 'System\Login\Loginsecurity.PAS',
  LoginsecurityDataAccess in 'System\Login\LoginsecurityDataAccess.PAS',
  LoginsecurityFrame in 'System\Login\LoginsecurityFrame.PAS' {FraLoginsecurity: TFrame},
  LoginsecurityInterfaces in 'System\Login\LoginsecurityInterfaces.PAS',
  LoginsecuritySection in 'System\Login\LoginsecuritySection.PAS',
  PasswordHistoryFrame in 'System\Password\PasswordHistoryFrame.PAS',
  PasswordHistorySection in 'System\Password\PasswordHistorySection.PAS',
  Passwordsecurity in 'System\Password\Passwordsecurity.PAS',
  PasswordsecurityDataAccess in 'System\Password\PasswordsecurityDataAccess.PAS',
  PasswordsecurityFrame in 'System\Password\PasswordsecurityFrame.PAS' {FraPasswordsecurity: TFrame},
  PasswordsecurityInterfaces in 'System\Password\PasswordsecurityInterfaces.PAS',
  MacroDataAccess in 'System\Macro\MacroDataAccess.PAS',
  Macroelement in 'System\Macro\Macroelement.PAS',
  MacroelementDataAccess in 'System\Macro\MacroelementDataAccess.PAS',
  MacroelementFrame in 'System\Macro\MacroelementFrame.PAS' {FraMacroelement: TFrame},
  MacroelementInterfaces in 'System\Macro\MacroelementInterfaces.PAS',
  MacroelementSection in 'System\Macro\MacroelementSection.PAS',
  MacroFrame in 'System\Macro\MacroFrame.PAS' {FraMacro: TFrame},
  MacroSection in 'System\Macro\MacroSection.PAS',
  MenutoolbarSection in 'System\Menu\MenutoolbarSection.PAS',
  Menutoolbar in 'System\Menu\Menutoolbar.PAS',
  MenutoolbarDataAccess in 'System\Menu\MenutoolbarDataAccess.PAS',
  MenutoolbarFrame in 'System\Menu\MenutoolbarFrame.PAS' {FraMenutoolbar: TFrame},
  MenutoolbarInterfaces in 'System\Menu\MenutoolbarInterfaces.PAS',
  ModuleBrowse in 'System\Module\ModuleBrowse.pas' {FrmModuleBrowse},
  ModuleDataAccess in 'System\Module\ModuleDataAccess.PAS',
  ModuleEdit in 'System\Module\ModuleEdit.pas' {FrmModuleEdit},
  ModuleFrame in 'System\Module\ModuleFrame.PAS' {FraModule: TFrame},
  ModuleManager in 'System\Module\ModuleManager.pas',
  ModuleSection in 'System\Module\ModuleSection.PAS',
  ModuleValue in 'System\Module\ModuleValue.pas',
  OutstandingSection in 'System\Notify\OutstandingSection.PAS',
  Notification in 'System\Notify\Notification.PAS',
  NotificationDataAccess in 'System\Notify\NotificationDataAccess.PAS',
  NotificationFrame in 'System\Notify\NotificationFrame.PAS' {FraNotification: TFrame},
  NotificationInterfaces in 'System\Notify\NotificationInterfaces.PAS',
  NotificationIs in 'System\Notify\NotificationIs.PAS',
  NotificationIsDataAccess in 'System\Notify\NotificationIsDataAccess.PAS',
  NotificationIsFrame in 'System\Notify\NotificationIsFrame.PAS' {FraNotificationIs: TFrame},
  NotificationIsInterfaces in 'System\Notify\NotificationIsInterfaces.PAS',
  NotificationIsSection in 'System\Notify\NotificationIsSection.PAS',
  NotificationSection in 'System\Notify\NotificationSection.PAS',
  Notify in 'System\Notify\Notify.PAS',
  NotifyDataAccess in 'System\Notify\NotifyDataAccess.PAS',
  NotifyFrame in 'System\Notify\NotifyFrame.PAS' {FraNotify: TFrame},
  NotifySection in 'System\Notify\NotifySection.PAS',
  Outstanding in 'System\Notify\Outstanding.PAS',
  OutstandingDataAccess in 'System\Notify\OutstandingDataAccess.PAS',
  OutstandingFrame in 'System\Notify\OutstandingFrame.PAS' {FraOutstanding: TFrame},
  OutstandingInterfaces in 'System\Notify\OutstandingInterfaces.PAS',
  LoginHistory in 'System\Login\LoginHistory.PAS',
  LoginHistoryDataAccess in 'System\Login\LoginHistoryDataAccess.PAS',
  OperatorFrame in 'System\Operator\OperatorFrame.PAS' {FraOperator: TFrame},
  OperatorSection in 'System\Operator\OperatorSection.PAS',
  Operatorstatus in 'System\Operator\Operatorstatus.PAS',
  OperatorstatusDataAccess in 'System\Operator\OperatorstatusDataAccess.PAS',
  OperatorstatusFrame in 'System\Operator\OperatorstatusFrame.PAS' {FraOperatorstatus: TFrame},
  OperatorstatusInterfaces in 'System\Operator\OperatorstatusInterfaces.PAS',
  OperatorstatusSection in 'System\Operator\OperatorstatusSection.PAS',
  ProductSection in 'System\Product\ProductSection.PAS',
  ProductFrame in 'System\Product\ProductFrame.PAS',
  Productmodule in 'System\Product\Productmodule.PAS',
  ProductmoduleDataAccess in 'System\Product\ProductmoduleDataAccess.PAS',
  ProductmoduleFrame in 'System\Product\ProductmoduleFrame.PAS',
  ProductmoduleInterfaces in 'System\Product\ProductmoduleInterfaces.PAS',
  ProductmoduleSection in 'System\Product\ProductmoduleSection.PAS',
  Product in 'System\Product\Product.PAS',
  ProductDataAccess in 'System\Product\ProductDataAccess.PAS',
  ProductInterfaces in 'System\Product\ProductInterfaces.PAS',
  Tag in 'System\Tag\Tag.pas',
  Control in 'System\Control\Control.PAS',
  ControlDataAccess in 'System\Control\ControlDataAccess.PAS',
  ControlFrame in 'System\Control\ControlFrame.PAS' {FraControl: TFrame},
  ControlInterfaces in 'System\Control\ControlInterfaces.PAS',
  ControlIs in 'System\Control\ControlIs.PAS',
  ControlIsDataAccess in 'System\Control\ControlIsDataAccess.PAS',
  ControlIsFrame in 'System\Control\ControlIsFrame.PAS' {FraControlIs: TFrame},
  ControlIsInterfaces in 'System\Control\ControlIsInterfaces.PAS',
  ControlIsSection in 'System\Control\ControlIsSection.PAS',
  ControlSection in 'System\Control\ControlSection.PAS',
  debScreenEdit in 'System\Security\debScreenEdit.pas' {FrmdebScreenEdit},
  MenuSecurity in 'System\Security\MenuSecurity.pas',
  Screen in 'System\Screen\Screen.PAS',
  ScreenDataAccess in 'System\Screen\ScreenDataAccess.PAS',
  ScreenFrame in 'System\Screen\ScreenFrame.PAS' {FraScreen: TFrame},
  ScreenInterfaces in 'System\Screen\ScreenInterfaces.PAS',
  ScreenSection in 'System\Screen\ScreenSection.PAS',
  SecurityEvent in 'System\Security\SecurityEvent.PAS',
  SecurityEventDataAccess in 'System\Security\SecurityEventDataAccess.PAS',
  SecurityEventFrame in 'System\Security\SecurityEventFrame.PAS' {FraSecurityEvent: TFrame},
  SecurityEventInterfaces in 'System\Security\SecurityEventInterfaces.PAS',
  SecurityEventSection in 'System\Security\SecurityEventSection.PAS',
  Security in 'System\Security\Security.PAS',
  SecurityDataAccess in 'System\Security\SecurityDataAccess.PAS',
  SecurityFrame in 'System\Security\SecurityFrame.PAS' {FraSecurity: TFrame},
  SecurityGroup in 'System\Security\SecurityGroup.PAS',
  SecurityGroupDataAccess in 'System\Security\SecurityGroupDataAccess.PAS',
  SecurityGroupFrame in 'System\Security\SecurityGroupFrame.PAS' {FraSecurityGroup: TFrame},
  SecurityGroupInterfaces in 'System\Security\SecurityGroupInterfaces.PAS',
  SecurityGroupSection in 'System\Security\SecurityGroupSection.PAS',
  SecurityInterfaces in 'System\Security\SecurityInterfaces.PAS',
  Securitymember in 'System\Security\Securitymember.PAS',
  SecuritymemberDataAccess in 'System\Security\SecuritymemberDataAccess.PAS',
  SecuritymemberFrame in 'System\Security\SecuritymemberFrame.PAS' {FraSecuritymember: TFrame},
  SecuritymemberInterfaces in 'System\Security\SecuritymemberInterfaces.PAS',
  SecuritymemberSection in 'System\Security\SecuritymemberSection.PAS',
  SecuritySection in 'System\Security\SecuritySection.PAS',
  ItemHistoryFrame in 'Element\Tracking\ItemHistoryFrame.PAS',
  ItemHistorySection in 'Element\Tracking\ItemHistorySection.PAS',
  ItemSnapshot in 'Element\Item\ItemSnapshot.PAS',
  ItemSnapshotDataAccess in 'Element\Item\ItemSnapshotDataAccess.PAS',
  ItemSnapshotFrame in 'Element\Item\ItemSnapshotFrame.PAS' {FraItemSnapshot: TFrame},
  ItemSnapshotInterfaces in 'Element\Item\ItemSnapshotInterfaces.PAS',
  PasswordSecurityTypes in 'System\Password\PasswordSecurityTypes.pas',
  LoginRecordingTypes in 'System\Login\LoginRecordingTypes.pas',
  LoginSecurityTypes in 'System\Login\LoginSecurityTypes.pas',
  AttributeIsTypes in 'Element\Attribute\AttributeIsTypes.pas',
  DefaultBrowse in 'Interface\Browse\DefaultBrowse.pas',
  DefaultBrowseInterfaces in 'Interface\Browse\DefaultBrowseInterfaces.pas',
  SystemNoInterfaces in 'System\SystemNo\SystemNoInterfaces.pas',
  SystemNoConstants in 'System\SystemNo\SystemNoConstants.pas',
  ContactIs in 'System\Contact\ContactIs.PAS',
  ContactIsDataAccess in 'System\Contact\ContactIsDataAccess.PAS',
  ContactIsFrame in 'System\Contact\ContactIsFrame.PAS' {FraContactIs: TFrame},
  ContactIsInterfaces in 'System\Contact\ContactIsInterfaces.PAS',
  ContactIsSection in 'System\Contact\ContactIsSection.PAS',
  llObject in 'Components\llObject.pas',
  AuditManager in 'System\Audit\AuditManager.pas',
  AuditManagerInterfaces in 'System\Audit\AuditManagerInterfaces.pas',
  AuditManagerDataAccess in 'System\Audit\AuditManagerDataAccess.pas',
  AuditManagerDataAccessInterfaces in 'System\Audit\AuditManagerDataAccessInterfaces.pas',
  LoginInterfaces in 'System\Login\LoginInterfaces.pas',
  EditInterfaces in 'Interface\Edit\EditInterfaces.pas',
  Edit in 'Interface\Edit\Edit.pas',
  EditTemplate in 'Interface\Edit\EditTemplate.pas' {FrmEditTemplate},
  Editee in 'Interface\Edit\Editee.pas',
  SelectTemplate in 'Interface\Select\SelectTemplate.pas' {FrmSelectTemplate},
  Select in 'Interface\Select\Select.pas',
  SelectInterfaces in 'Interface\Select\SelectInterfaces.pas',
  ScreenManager in 'System\Screen\ScreenManager.pas',
  ScreenManagerInterfaces in 'System\Screen\ScreenManagerInterfaces.pas',
  CompoundManager in 'Element\Compound\CompoundManager.pas',
  CompoundManagerInterfaces in 'Element\Compound\CompoundManagerInterfaces.pas',
  IsotopeManager in 'Element\Isotope\IsotopeManager.pas',
  IsotopeManagerInterfaces in 'Element\Isotope\IsotopeManagerInterfaces.pas',
  ElementManagerInterfaces in 'Element\Element\ElementManagerInterfaces.pas',
  ElementManager in 'Element\Element\ElementManager.pas',
  StatusManager in 'Element\Status\StatusManager.pas',
  StatusManagerInterfaces in 'Element\Status\StatusManagerInterfaces.pas',
  AssociateManager in 'Element\Associate\AssociateManager.pas',
  AssociateManagerInterfaces in 'Element\Associate\AssociateManagerInterfaces.pas',
  AttributeStringFrame in 'Element\Attribute\AttributeStringFrame.pas' {FraAttributeString: TFrame},
  AttributeDateTimeFrame in 'Element\Attribute\AttributeDateTimeFrame.pas' {FraAttributeDateTime: TFrame},
  AttributeMemoFrame in 'Element\Attribute\AttributeMemoFrame.pas' {FraAttributeMemo: TFrame},
  AttributeBooleanFrame in 'Element\Attribute\AttributeBooleanFrame.pas' {FraAttributeBoolean: TFrame},
  AttributeAssociateFrame in 'Element\Attribute\AttributeAssociateFrame.pas' {FraAttributeAssociate: TFrame},
  SectionInterfaces in 'Interface\section\SectionInterfaces.pas',
  Section in 'Interface\Section\Section.pas',
  ChapterInterfaces in 'Interface\Chapter\ChapterInterfaces.pas',
  Chapter in 'Interface\Chapter\Chapter.pas',
  BookInterfaces in 'Interface\book\BookInterfaces.pas',
  Book in 'Interface\book\Book.pas',
  FrameHelper in 'Interface\Frame\FrameHelper.pas',
  DefaultBookInterfaces in 'Interface\book\DefaultBookInterfaces.pas',
  DefaultBook in 'Interface\book\DefaultBook.pas',
  ItemSection in 'Element\Item\ItemSection.PAS',
  ItemSnapshotSection in 'Element\Item\ItemsnapshotSection.PAS',
  ItemIsSection in 'Element\Item\ItemIsSection.PAS',
  ItemSectionInterfaces in 'Element\Item\ItemSectionInterfaces.pas',
  BCSInterfaces in 'Interface\book\BCSInterfaces.pas',
  BCS in 'Interface\book\BCS.pas',
  DefaultChapterInterfaces in 'Interface\Chapter\DefaultChapterInterfaces.pas',
  DefaultChapter in 'Interface\Chapter\DefaultChapter.pas',
  MoveManagerInterfaces in 'Interface\Action\Move\MoveManagerInterfaces.pas',
  MoveManager in 'Interface\Action\Move\MoveManager.pas',
  LoginHistoryTypes in 'System\Login\LoginHistoryTypes.pas';

{$R *.RES}

begin
  Application.ShowMainForm := False;
  Application.HelpFile := 'STACY.HLP';
  Application.Title := 'Stacy - Item Tracking';
  Application.CreateForm(TFrmStacyMain, FrmStacyMain);
  Application.Initialize;
  Application.Run;
{$IFDEF DontCompile}
  don't compile!
{$ENDIF}
end.
